### ISSUE TITLE
Geth crash - 'panic: close of closed channel'

### ISSUE THREAD

**Issue by sonyjoseph** [ethereum/go-ethereum#1084]
I keep getting this error consistently.It seems to happen after the chain in sycn'd up.  Does anyone what might be causing it:

I0523 07:04:07.413749 2746 chain_manager.go:670] Fork detected @ e5cfa075. Reorganising chain from #423771 4bd93b8f to 2068e3d2
I0523 07:04:07.414364 2746 chain_manager.go:627] imported 1 block(s) (0 queued 0 ignored) in 6.973138ms. #423771 [2068e3d2 / 2068e3d2]
I0523 07:04:07.418502 2746 worker.go:342] commit new work on block 423772 with 1 txs & 0 uncles
panic: close of closed channel

goroutine 1858 [running]:
github.com/ethereum/go-ethereum/miner.(*CpuAgent).update(0xc20ad92a40)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:65 +0xd7
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).Start
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/miner/agent.go:56 +0x134

goroutine 1 [select]:
github.com/peterh/liner.(*State).readNext(0xc2081d1e60, 0x0, 0x0, 0x0, 0x0)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/input.go:140 +0x2a1d
github.com/peterh/liner.(*State).Prompt(0xc2081d1e60, 0xc8a230, 0x2, 0x0, 0x0, 0x0, 0x0)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/peterh/liner/line.go:494 +0x443
main.(*jsre).interactive(0xc20c6fa780)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/js.go:187 +0x72
main.console(0xc20807a1c0)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:331 +0x3c4
github.com/codegangsta/cli.Command.Run(0xc9e8f0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdb7770, 0x30, 0xf46bd0, ...)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc20816c000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xdf6
main.main()
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:288 +0x80

goroutine 6 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:65 +0x6d1
created by github.com/ethereum/go-ethereum/logger.init·1
/build/buildd/ethereum-9.21.1+510SNAPSHOT20150516160201trusty/obj-x86_64-linux-gnu/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25

Thanks

**Comment by zelig** [comment]
fixed in https://github.com/ethereum/go-ethereum/commit/677796b3517782dd530b7a1a7d9dfd16b643404c <- https://github.com/ethereum/go-ethereum/pull/1031

**Comment by sonyjoseph** [comment]
Thanks... I tried running it with merged code but still get the same issues. Is there anything else I should be doing such as upgrading the db or cleaning up the .ethereum folder
