### ISSUE TITLE
improve error message when starting a second instance of geth

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#1564]
"Fatal: extra db err: resource temporarily unavailable" indicates another geth instance running. 
should say that.

**Comment by tgerring** [comment]
Maybe related to #1634

**Comment by karalabe** [comment]
This was fixed, and will be further refined by the customizable protocol stacks PR https://github.com/ethereum/go-ethereum/pull/1970.

**Comment by JohnAllen** [comment]
Is this really fixed?  Just ran into it.  Running the same geth command when an instance is already running still throws `Fatal: Error starting protocol stack: resource temporarily unavailable`

 `geth 1.6.7`
