### ISSUE TITLE
No discv4 seed nodes found

### ISSUE THREAD

**Issue by hameleonick** [ethereum/go-ethereum#15823]
Hi all,

I have next problem, each time I receive "No discv4 seed nodes found". Could you clarify it?
More details below:

#### System information

Geth version: `1.7.3`
OS & Version: OSX 10.12.6
(tested also on Ubuntu and same result)

#### Expected behaviour
Start geth in fast sync mode

#### Actual behaviour
All time I received: 
No discv4 seed nodes found

#### Steps to reproduce the behaviour
I start command: 
geth --syncmode fast --cache 2048 --verbosity 4 --ipcpath ~/ipc/geth.ipc --testnet --networkid=3

#### Backtrace
DEBUG[01-06|14:11:28] FS scan times                            list=125.703µs set=2.435µs diff=3.798µs
WARN [01-06|14:11:28] No etherbase set and no accounts found as default
INFO [01-06|14:11:28] Starting peer-to-peer node               instance=Geth/v1.7.3-stable/darwin-amd64/go1.9.2
INFO [01-06|14:11:28] Allocated cache and file handles         database=/Users/Library/Ethereum/testnet/geth/chaindata cache=2048 handles=1024
INFO [01-06|14:11:28] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}"
INFO [01-06|14:11:28] Disk storage enabled for ethash caches   dir=/Users/Library/Ethereum/testnet/geth/ethash count=3
INFO [01-06|14:11:28] Disk storage enabled for ethash DAGs     dir=/Users/.ethash                              count=2
INFO [01-06|14:11:28] Initialising Ethereum protocol           versions="[63 62]" network=3
INFO [01-06|14:11:28] Loaded most recent local header          number=0 hash=419410…ca4a2d td=1048576
INFO [01-06|14:11:28] Loaded most recent local full block      number=0 hash=419410…ca4a2d td=1048576
INFO [01-06|14:11:28] Loaded most recent local fast block      number=0 hash=419410…ca4a2d td=1048576
DEBUG[01-06|14:11:28] Reinjecting stale transactions           count=0
INFO [01-06|14:11:28] Loaded local transaction journal         transactions=0 dropped=0
INFO [01-06|14:11:28] Regenerated local transaction journal    transactions=0 accounts=0
DEBUG[01-06|14:11:28] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [01-06|14:11:28] Starting P2P networking
INFO [01-06|14:11:28] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
INFO [01-06|14:11:28] UDP listener up                          self=enode://3f4e43224fa636c9a91eef310d84a757f5369c5f05ae22705033b0f39da5465d63406ca1c007ed8c49654b2da3cc7a5d256b6c6d73b84daa3a35ba933dc33d42@79.187.183.14:30303
INFO [01-06|14:11:28] RLPx listener up                         self=enode://3f4e43224fa636c9a91eef310d84a757f5369c5f05ae22705033b0f39da5465d63406ca1c007ed8c49654b2da3cc7a5d256b6c6d73b84daa3a35ba933dc33d42@79.187.183.14:30303
DEBUG[01-06|14:11:28] InProc registered *node.PrivateAdminAPI under 'admin'
DEBUG[01-06|14:11:28] InProc registered *node.PublicAdminAPI under 'admin'
DEBUG[01-06|14:11:28] InProc registered *debug.HandlerT under 'debug'
DEBUG[01-06|14:11:28] InProc registered *node.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] InProc registered *node.PublicWeb3API under 'web3'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicEthereumAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicBlockChainAPI under 'eth'
DEBUG[01-06|14:11:28] Executing EVM call finished              runtime=312.146µs
DEBUG[01-06|14:11:28] Release oracle not found                 contract=0xFA7B9770Ca4cb04296Cac84F37736d4041251CDF
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicTransactionPoolAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicTxPoolAPI under 'txpool'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PrivateDebugAPI under 'debug'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicAccountAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PrivateAccountAPI under 'personal'
DEBUG[01-06|14:11:28] InProc registered *eth.PublicEthereumAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *eth.PublicMinerAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *downloader.PublicDownloaderAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *eth.PrivateMinerAPI under 'miner'
DEBUG[01-06|14:11:28] InProc registered *filters.PublicFilterAPI under 'eth'
DEBUG[01-06|14:11:28] InProc registered *eth.PrivateAdminAPI under 'admin'
DEBUG[01-06|14:11:28] InProc registered *eth.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] InProc registered *eth.PrivateDebugAPI under 'debug'
DEBUG[01-06|14:11:28] InProc registered *ethapi.PublicNetAPI under 'net'
DEBUG[01-06|14:11:28] IPC registered *node.PrivateAdminAPI under 'admin'
DEBUG[01-06|14:11:28] IPC registered *node.PublicAdminAPI under 'admin'
DEBUG[01-06|14:11:28] IPC registered *debug.HandlerT under 'debug'
DEBUG[01-06|14:11:28] IPC registered *node.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] IPC registered *node.PublicWeb3API under 'web3'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicEthereumAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicBlockChainAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicTransactionPoolAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicTxPoolAPI under 'txpool'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PrivateDebugAPI under 'debug'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicAccountAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PrivateAccountAPI under 'personal'
DEBUG[01-06|14:11:28] IPC registered *eth.PublicEthereumAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *eth.PublicMinerAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *downloader.PublicDownloaderAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *eth.PrivateMinerAPI under 'miner'
DEBUG[01-06|14:11:28] IPC registered *filters.PublicFilterAPI under 'eth'
DEBUG[01-06|14:11:28] IPC registered *eth.PrivateAdminAPI under 'admin'
DEBUG[01-06|14:11:28] IPC registered *eth.PublicDebugAPI under 'debug'
DEBUG[01-06|14:11:28] IPC registered *eth.PrivateDebugAPI under 'debug'
DEBUG[01-06|14:11:28] IPC registered *ethapi.PublicNetAPI under 'net'
INFO [01-06|14:11:28] IPC endpoint opened: /Users/ipc/geth.ipc
INFO [01-06|14:11:28] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.1.1)
DEBUG[01-06|14:11:29] No discv4 seed nodes found
DEBUG[01-06|14:11:33] No discv4 seed nodes found
DEBUG[01-06|14:11:37] No discv4 seed nodes found
DEBUG[01-06|14:11:41] No discv4 seed nodes found
DEBUG[01-06|14:11:45] No discv4 seed nodes found
DEBUG[01-06|14:11:48] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[01-06|14:11:49] No discv4 seed nodes found
````
[backtrace]
````

**Comment by larcai** [comment]
+1

**Comment by larcai** [comment]
it seems like the bootnodes are refusing connections...  my network/firewall is fine since I can sync with MainNet

Dial error  task="dyndial 20c9ad97c081d633 52.169.14.227:30303" err="dial tcp 52.169.14.227:30303: connectex: No connection could be made because the target machine actively refused it."

**Comment by hameleonick** [comment]
resolved with 
admin.addPeer("enode://256405c3af6b9369c84bb90927c99a1edabe061a62e3c7bec19f23e3c8ad6fea9cc5c47e174435bbb415852e344ad9d7bb61c158e69fb5f29f16cc787f85cf2c@92.111.252.195:63451");
admin.addPeer("enode://27f7328ef96a15f6f47ddeba8ba2a50952e430a3f294bd0e479e47239123167ba67fb46057405b1baa1716ee8ef5cd58b982b241e82d1fd8f5891d77f1a84a51@85.223.209.56:51938");
admin.addPeer("enode://42de7d88a5473d6317f1826ca87689b2b9566a2ece72da0c78d529b61295264b2aec8c13fc3e2d1f5d05fbfb0c2ab98af2c64a6f6fa9dc7236b28d97323d2ba4@136.62.220.147:30303");
admin.addPeer("enode://6991bbef05ca85e9cb0cfab1b8f9427500bb004ff21edb189760d146bf5f37015202b565e0af752f2975f3f8bdc672ab8b39d378b0911874883ac70cdf23c83d@121.122.127.186:45534");
admin.addPeer("enode://9e99e183b5c71d51deb16e6b42ac9c26c75cfc95fff9dfae828b871b348354cbecf196dff4dd43567b26c8241b2b979cb4ea9f8dae2d9aacf86649dafe19a39a@51.15.79.176:41462");
admin.addPeer("enode://9eccca5941e191de1f43345c7bbcb8a0a77fe383329d5f85da72d445f72bb9561768118443604b474022ce7e9dc58779acc8486fb882801e61a800ca0c089930@140.112.238.158:37162");
admin.addPeer("enode://f55d3f3a5e21bb4e0bcd046ccc880f4e79bddee570a9909c72de61470b48e0309d38460b28408c50d689cf4629a3bb0877f7556d142950cb3d3b3251ced405a1@52.212.59.171:30303");

Thx

**Comment by madhubajpai** [comment]
Facing exactly same problem 'No discv4 seed nodes found' for Ropsten testnet on Ubuntu. Node synchronization works fine with mainnet though.

After following the suggestion of homeleonick, did AddPeer() but getting error "Resolving node failed"

Does not appear to be a port block issue as node is able to sync with Mainnet.

Command: geth --testnet --fast --rpc --rpccorsdomain '*' console --cache=1024 --rpcaddr 192.168.8.15 --networked=3

Also, does anybody has link of Ropsten genesis json file? couldn't find a working link anywhere.

Please suggest.

**Comment by pratgen** [comment]
I could not resolve the issue.
I uninstalled geth/reinstall but still no luck.
On the same machine, rinkeby works very well.
There is no firewall installed on my machine.
Similar issue by faced by some other person 
https://ethereum.stackexchange.com/questions/36636/geth-v1-7-2-not-connecting-to-peers-on-ropsten/36791#36791
You may check the trace here.
[trace.txt](https://github.com/ethereum/go-ethereum/files/1645578/trace.txt)

**Comment by hameleonick** [comment]
Hi all,

If you have some issues with getting new blocks or Ethereum handshake failed or something like this. I would recommend you watch for this repo https://gist.github.com/rfikki/. You can find there (I hope that always) list of newly available peers that I believe will resolve your issues.

**Comment by webjunkie01** [comment]
@hameleonick thanks ;).

**Comment by 4ntoine** [comment]
had the same issue with 1.7.3, works as expected with 1.8.10
