### ISSUE TITLE
Many Metrics appear broken in 1.7.x.

### ISSUE THREAD

**Issue by ryanschneider** [ethereum/go-ethereum#15944]
#### System information

Geth version: `1.7.3-stable-4bb3c89d`
```
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.9
```
OS & Version: Linux
Commit hash : 1.7.3

#### Expected behaviour

`geth monitor` should work, and `debug.metrics(true).txpool` should return metrics values.

#### Actual behaviour

`geth monitor` fails:

```
geth monitor
Fatal: Metric pattern trie/cachemiss resolved to unexpected type: string
```

and `debug.metrics(true).txpool` (and other sub-objects) returns invalid metrics:

```
> debug.metrics(true).txpool
{
  invalid: "Unknown metric type",
  pending: {
    discard: "Unknown metric type",
    nofunds: "Unknown metric type",
    ratelimit: "Unknown metric type",
    replace: "Unknown metric type"
  },
  queued: {
    discard: "Unknown metric type",
    nofunds: "Unknown metric type",
    ratelimit: "Unknown metric type",
    replace: "Unknown metric type"
  },
  underpriced: "Unknown metric type"
}
```

It appears that these subsystems don't know about the `Counter` and `RegisteredCounter` types.

I'll put it on my personal roadmap to try to implement the changes necessary to support these, but any pointers from the core team on what might be the issue would be greatly appreciated!

Thanks,
Ryan

**Comment by nonsense** [comment]
@ryanschneider `geth monitor` has been fixed on `master`, and I can see `debug.metrics(true)` returning `Counter` types. Let me know if you still have troubles with it once you upgrade to `master`.

**Comment by ryanschneider** [comment]
Awesome thanks, I tried 1.8 and still see the issue but haven't had a chance to build and test `master` yet, I'll give that a go as soon as I can.

**Comment by ryanschneider** [comment]
Confirmed this is fixed in `master` (but not in 1.8.1).  Thanks!
