### ISSUE TITLE
Geth falsly reporting zero balance on synced transaction

### ISSUE THREAD

**Issue by rritoch** [ethereum/go-ethereum#16496]
Geth falsly reporting zero balance on synced transaction. The "attach" session below under actual behavior verifies that geth is not functioning properly.

#### System information

Geth version: 1.8.3-stable
OS & Version: Windows/Linux
Commit hash : 329ac18ef617d0238f71637bffe78f028b0f13f7

Version: 1.8.3-stable
Git Commit: 329ac18ef617d0238f71637bffe78f028b0f13f7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: windows
GOPATH=
GOROOT=C:\go

#### Expected behaviour

`eth.getBalance("0x50414d4d3d26048f6d4461730447f843012ad3af")` returning non-zero balance

#### Actual behaviour

```

> eth.accounts
["0x2062f1ec1b10aece7ae6a8e3d25e4ddd78322bf0", "0x50414d4d3d26048f6d4461730447f843012ad3af"]
> eth.getBalance(eth.accounts[1])
0
> eth.getTransaction("0xb78bef37c80edb552ce33d544e5c13ce83e40bbea1892fc4377e5e881b69c127")
{
  blockHash: "0x46847dc4322ef5a31e2fdfa57e96fa6c84c5482c7b9ed553594c7259e3a03bb5",
  blockNumber: 5372932,
  from: "0x2a65aca4d5fc5b5c859090a6c34d164135398226",
  gas: 50000,
  gasPrice: 4000000000,
  hash: "0xb78bef37c80edb552ce33d544e5c13ce83e40bbea1892fc4377e5e881b69c127",
  input: "0x",
  nonce: 3264462,
  r: "0xc2b3aaeb7bd36f167523070cb881f98068f628b05bd6baf320061d129ed7da08",
  s: "0x44d5c4751c533d69d7276eacca268f80dee02604765319761340959ef7b4524a",
  to: "0x50414d4d3d26048f6d4461730447f843012ad3af",
  transactionIndex: 7,
  v: "0x26",
  value: 50086850000000000
}
>

```
#### Steps to reproduce the behaviour

Attempt to use geth to view account balance

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
As long as `knownStates` > `pulledStates`, the state trie has not yet been downloaded, so no state is accessible. You'll need to wait until every node of the state trie is downloaded before you'll see any state.

**Comment by rritoch** [comment]
@karalabe I've been fully synced many times without showing a balance.  This seems to be caused by fast mode. I was using mist wallet which comes with geth and therefore defaults to fast.  I finally tried to engineer a correct sync by uninstalling everything except backups and starting over using a full sync. This seems to be working so far.  Fast sync NEVER entered full mode even after fully synced. That is probably the core of the bug.

**Comment by holiman** [comment]
That last snippet of output shows a full-sync from genesis, but has only reached block 1.2M. Doing that will take minimum 100 hours, probably a lot longer. If you would have waited out the fast-sync, it probably would have worked. 

> I've been fully synced many times without showing a balance.

How can you tell?

**Comment by rritoch** [comment]
The eth.syncing returned false and I had been syncing for nearly a week (24/7) in fast mode. When I originally had no balance showing and needed to resync I had been syncing in fast mode for over a month non-stop.

**Comment by karalabe** [comment]
Older releases had a bug with `eth_syncing` reporting false sometimes. It was fixed in 1.8.3 afaik. As for syncing being doe or not, you can always tell whether you see "Imported state entries" logs or not. As long as those are being displayed, you're not in sync yet.

> I had been syncing in fast mode for over a month non-stop.

Are you on an SSD or HDD? An HDD currently is not usable to sync with

**Comment by ccding** [comment]
I had the same issue. Just curious, is HDD a problem? If it is, then I got it.

**Comment by rritoch** [comment]
I was using HDD, I'm now using Windows 10 two-way mirror Raid with 2 X HDD, the speed is double but I still have a ways before sync. I'm less than a year behind now at block 3943563 but I am no longer using fast mode since that appears to be broken as per this bug. I am not going to try to continue using FAST mode which appears to be the problem so you will need other people with this problem to track if it has been resolved.

**Comment by rritoch** [comment]
I'm still syncing.  I'd say this is a scam to sell SSD drives but I'm seeing complaints here regarding SSD's also.  So here we are, 28 days later, syncing 24/7 on mirrord storage space (windows raid) and not yet synced.

{
  currentBlock: 4474824,
  highestBlock: 5658093,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 4474794
}

To be exact I'm 202 days behind the head of this garbage blockchain technology.  In this time I've been able to learn the GO language and start hacking my wallet.  The paranoid locking is obviously the problem but unfortunately I don't have a good enough understanding of the data flow to know which code I can unlock.  I did increase the internal "ideal batch size" to 1Mb.  Secondly I'd say that 2Mb per file is way too small considering the resource manager says there's an average of about 8Mb per second being transferred to the Hard drive, I don't know how many file handles it has open but based on the file size it must be at least 4 so the hard drive is likely wasting a lot of time waiting for the disk to spin around to where the files are.  If only I could find a way to resize this database I would NEVER go with 2Mb files, maybe 64/128Mb, but at 2Mb I doubt windows explorer can even open the folder at this point. This architecture is either based on incompetance or a scam to sell hardware. Whatever the case it WILL be hacked, code this bad can easily be hacked.  I already found at least one bug which I know would cause the syncing to freeze because a lock is created and never unlocked... Just bad code and bad architecture, that is what is wrong with geth.

**Comment by jjhesk** [comment]
does it work faster? "--trie-cache-gens=480" does this one

**Comment by Archie1978** [comment]
hello,  It's strange, I have the same thing. But I noticed that the genesis portfolios were not at 0.
Example:
> web3.eth.getBalance("0x2489ac126934D4d6a94Df08743Da7b7691e9798E");
1e+21

But actually, there are 300ether

**Comment by holiman** [comment]
@rritoch we've attempted larger file sizes many times. It appears you're doing full sync (block-by-block). Larger leveldb filesizes means that the compaction overhead will blow up. 
Here's a recent attempt: https://github.com/ethereum/go-ethereum/pull/19600  (did not fare well). 
Here's an older attempt: https://github.com/ethereum/go-ethereum/pull/18203 

> I already found at least one bug which I know would cause the syncing to freeze because a lock is created and never unlocked... 

If so, please file a ticket or a PR. 

@Archie1978 the genesis contains the ether sold in the Ethereum presale

**Comment by holiman** [comment]
Closing this. Seems the original report was not actually a synced node, and this is expected behaviour on an unsynced node
