### ISSUE TITLE
accounts: unlock multiple accounts fails

### ISSUE THREAD

**Issue by danielnovy** [ethereum/go-ethereum#1785]
When trying to use ``--unlock="0 1"`` geth fails with the message: `Fatal: Unlock account failed 'Decryption failed: MAC mismatch'`. The first account is unlocked and the message `Account '0' unlocked` is printed. 

It's important to note that `unlock="0"` AND `unlock="1"` both works! Also, if you invert the order ("1 0" instead of "0 1"), it prints `Account '1' unlocked` and then fails to unlock second account with same message. So, the problem is clearly related to unlock multiple accounts and problem always happens on second account.

**Comment by zelig** [comment]
I believe this has already been fixed in #1840

**Comment by karalabe** [comment]
Closing if supposedly fixed. Please reopen if it's not the case. Also note, an upcoming PR will change the account list to comma separated values instead of space separated ones. This is a general move towards eliminating whitespace from within CLI arguments as they cause significant pains when passing through different environments (e.g. bash -> go -> docker -> bash).

**Comment by danielnovy** [comment]
Sorry for my late reply! Just tried it now and it's still not working in version `1.4.0-unstable`. So, please, reopen the issue since I don't have the privileges to do so. Thanks!

**Comment by karalabe** [comment]
I'll take a look

**Comment by javgh** [comment]
I'm also seeing this with geth 1.3.5 - trying to unlock more than one account via `--unlock "0 1"` fails on whatever account is listed second with a `'Decryption failed: MAC mismatch'` error, but only when used in combination with the `--password` option. When entering the passwords manually, both accounts are unlocked successfully. I'm also only seeing this error on one of my machines - another one also has two accounts and the same geth version and there it works. At the moment I don't see what the difference might be.

**Comment by thiagohortal** [comment]
Hello guys,
I am also getting this return: 'Decryption failed: MAC mismatch', any solution?
I am using web3 project.

Help!
