### ISSUE TITLE
Rinkeby Faucet Error - Unable to get ether

### ISSUE THREAD

**Issue by jamesjosephptea** [ethereum/go-ethereum#18342]
Hi there,

I am trying to get some ether for my hello world program . But could not get ether from rinkeby yet.
In the console i can see "WebSocket connection to 'wss://faucet.rinkeby.io/api' failed: Error during WebSocket handshake: Unexpected response code: 521" this error. This is happening with all browsers.

Would be great if some one can help me to sort the issue.

**Comment by ToMaple2** [comment]
I am affected by the same issue. I tried Chrome, Opera, and Brave browsers. Same Javascript error with all three.

**Comment by CarlosLanderas** [comment]
What is going on with the rinkeby faucet?

**Comment by ToMaple2** [comment]
I’ve noticed that the rinkeby.io <http://rinkeby.io/> website is down, Error 521

**Comment by jamesjosephptea** [comment]
Any idea when this will be up or how to take this up further ?

**Comment by CarlosLanderas** [comment]
I've notified about this to the people following my Ethereum development course but if you could give us at least some information about when this is going to be fixed would be great. Thanks!

**Comment by holiman** [comment]
Well, it's holiday season, so don't hold your breath. It might take a while to get it running again, unfortunately

**Comment by karalabe** [comment]
Fixed, disk got full.

**Comment by CarlosLanderas** [comment]
Thank you @karalabe

**Comment by Olshansk** [comment]
Seems like the issue is back. https://www.rinkeby.io/ is down and https://faucet.rinkeby.io/ cannot initialize a websocket.

Is there some place where status of the servers is published?

**Comment by karalabe** [comment]
Sorry about that, there were too many connections hammering the faucet and stats page and the reverse proxy started refusing new connections. Should work better now.

**Comment by Olshansk** [comment]
Got my ETH. Thank you @karalabe!

**Comment by loobj126** [comment]
The same issue here. Could you please assist if you have any spare ETH?
0x623CD18A2344476063Ee2f806EEdDdbcE9cd5499
