### ISSUE TITLE
Chain database corruption on Windows

### ISSUE THREAD

**Issue by jstefanop** [ethereum/go-ethereum#2289]
Started using geth 1.3.4 release binary and few hours after my blockchain got corrupted....keep getting errors below. Only way I know how to fix is to clear and re-download blockchain data. 

I0303 11:55:16.854551    6864 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x72cbb1fd got=0x44d430e2 [file=1008113.ldb]
I0303 11:55:27.469113    6864 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x72cbb1fd got=0x44d430e2 [file=1008113.ldb]

**Comment by adibas03** [comment]
+1

**Comment by fjl** [comment]
Thanks for the report. We haven't seen this issue so far. Please try the develop branch since it contains an updated version of go-leveldb.

You can get the binary for testing from https://builds.ethereum.org/builds/Windows%20Go%20develop%20branch/Geth-Win64-latest.zip

**Comment by obscuren** [comment]
Pling. Could you please try develop and report back.

**Comment by eharvest** [comment]
I am seeing the same issue with 1.3.5. Endless complaining about checksum mismatch. 
[amd64 Ubuntu 14.04]

```
I0326 12:52:23.759325    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:52:25.874790    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:52:34.123455    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:52:53.799699    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:03.179390    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:13.486868    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:36.329220    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:49.241467    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:55.248765    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:53:56.597844    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:54:06.017859    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:54:19.102403    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:54:36.169858    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:54:44.273455    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:55:02.355424    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:55:25.851030    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
I0326 12:55:28.707527    6691 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=337643): checksum mismatch, want=0xfd792f7 got=0x5e50a091 [file=000211.ldb]
```

**Comment by poonlit** [comment]
Having same issue on Win7, geth 1.3.5. Worked fine for weeks with 1.3.5, one day after geth had been running while I was on holiday and I tried to send a transaction (via geth attach) I started getting these errors. Didn't notice anything before I attempted the transaction.

Have checked Samsung Evo 840 SSD drive for filesystem errors (none) and SMART errors (none) and used geth removedb two times so it started downloading from scratch. 
Have stopped Trend AV and also made exception for appdata\roaming\ethereum folder before geth removedb, same issue.

Eventually (last time after block 330000 or so) it gets stuck with no peers to download from. If I restart, it keeps downloading more for a while. 

Will try more stuff.

**Comment by fjl** [comment]
I am marking this fixed now because leveldb has been updated in develop compared to master.

**Comment by jesse-git** [comment]
I get same behavior with not downloading from peers and same errors about repeated "handle is invalid" on 1.4.1 Windows 7 x64. Have tried a full day to sync and I'm only up to 826000.

**Comment by gorilla2112** [comment]
I downloaded the latest geth and still getting the synchronization error. I can only mine via pool, but cant access my wallet at the moment

**Comment by ardentra** [comment]
Getting the same. Tried both master and develop branches both have the same issue. Its going to really suck having to download the entire blockchain again.

**Comment by fjl** [comment]
We have a suspicion that this might be related to virus scanners after all. @gorilla2112, @ardentra do you have a virus scanner installed? If so, could you check whether it quarantined any ldb files?

**Comment by fjl** [comment]
DB corruption still occurs regularly for some users. The majority of reports about this are on Windows. We don't know why this happens. It looks like this is a problem with go-leveldb.

**Comment by fjl** [comment]
What we'd need is a standalone reproducer program that causes leveldb corruption.

**Comment by fjl** [comment]
We have updated to a newer versions version of goleveldb in geth 1.5.0.

**Comment by kadeeaguila** [comment]
has anyone found a fix for consistently getting 

CRIT [06-15|06:51:41] Failed to store last header's hash       err="leveldb/table: corruption on data-block (pos=1577926): checksum mismatch, want=0xc6b28462 got=0xe8e09878 [file=035058.ldb]"

how do we fix this? i keep doing removedb adn start over

i'm on MACOSX SAMSUNG EVO850

**Comment by adibas03** [comment]
@kadeeaguila what geth version are you running?

**Comment by kadeeaguila** [comment]
@adibas03 
Geth
Version: 1.6.5-stable

for the past 3 days have been downloading the chaindata then after all day i get a corrupted file
then i do removedb then start over. i do this aroun 3-4 times and try at night still this same

i've tried 
geth
geth --fast cache=1024
geth upgradedb

before i removedb AGAIN i want know what else i should do

**Comment by adibas03** [comment]
@kadeeaguila Since you have the most recent stable version, the most likely cause of the error could be your antivirus or network instability.  
Suggestions:  
-Check your network and antivirus  
-Check that you have the right geth architecture, that is sometimes the issue (32 bit or 64 bit)  
- If all the above do not work and you do not mind a light client, you could use the `--light` mode as against the `--fast` mode.
Hope this helps, as I have not experienced this issue in a while.

**Comment by kadeeaguila** [comment]
@adibas03 thank you for your answer

though i was able to download the full chaindata already before but a had to remove it.

will try to re-install geth just the same

will try one more time

**Comment by adibas03** [comment]
That is great news.

**Comment by niclash** [comment]
I managed to repair my leveldb with 
````
	opts := &goleveldbOpt.Options{}
	opts.ErrorIfMissing = true
	opts.ForceRebuild = true
	opts.DropTableOnRebuildError = true

	db, err := goleveldb.RecoverFile(DB_PATH, opts)
````
from https://github.com/rchunping/leveldb-tools/blob/master/main.go and that overcame the corruption complaint in Ethereum Wallet. Also, it only took sub-second to execute, so one could wonder if it shouldn't be built in to Ethereum Wallet.

**Comment by fjl** [comment]
@niclash That's good news and bad news. 

The good part: anything that makes a broken DB work again is worth looking into.

The bad part: I'm super unsure about `DropTableOnRebuildError`. This feature was added in the https://github.com/rchunping/goleveldb fork of goleveldb and it seems to just drop data. There are no guarantees if you do that. You might as well drop the whole DB.

**Comment by adamschmideg** [comment]
If the problem persists, please open a new issue.
