### ISSUE TITLE
geth does not exit

### ISSUE THREAD

**Issue by prateekreddy** [ethereum/go-ethereum#2526]
#### System information

Geth version: 1.3.5
OS & Version: Linux

#### Expected behaviour

The geth should exit when `if(true){exit}` is typed in geth console

#### Actual behaviour

It is not exiting and throws `ReferenceError: 'exit' is not defined`

#### Steps to reproduce the behaviour

1. Open geth console
2. type in `if(true){exit}`

**Comment by obscuren** [comment]
This has been fixed in 1.4, which will be released very soon.

**Comment by prateekreddy** [comment]
Thanks,

I just pulled v1.4.2 from release/1.4 but it was still giving the error. When can I expect the fix.

**Comment by fjl** [comment]
I don't know why @obscuren said that it is fixed in 1.4. 

`exit` is not a JavaScript statement. The console recognizes it as special input. There is no way to exit the console from JS code.

**Comment by prateekreddy** [comment]
Yes, can you make exit a function because it would be good if there is some way to stop the node when some events occur.

**Comment by prateekreddy** [comment]
@fjl @obscuren Can I know when can I expect the fix and also can you reopen the issue as this is not fixed yet.
