### ISSUE TITLE
Version 1.13.2 failes to build - maybe a bug?

### ISSUE THREAD

**Issue by peske** [ethereum/go-ethereum#28285]
I've just updated the dependencies in my project (sadly not opensource), and immediately I've started getting the following error when I try to build the project:

```
Error: ../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.2/crypto/kzg4844/kzg4844_gokzg.go:52:66: cannot convert blob (variable of type Blob) to type gokzg4844.Blob
Error: ../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.2/crypto/kzg4844/kzg4844_gokzg.go:64:64: cannot convert blob (variable of type Blob) to type gokzg4844.Blob
Error: ../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.2/crypto/kzg4844/kzg4844_gokzg.go:86:61: cannot convert blob (variable of type Blob) to type gokzg4844.Blob
Error: ../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.2/crypto/kzg4844/kzg4844_gokzg.go:97:53: cannot convert blob (variable of type Blob) to type gokzg4844.Blob
```

No other errors reported, in any other packages nor in my code. That's why I suspect that it may be a bug?

Thanks!

**Comment by karalabe** [comment]
Please check the versions in your go.mod file, you have something that clashes with each other. Perhaps you have pinned a version of gokzg that is different API wise from the one used inside Geth? Our code builds just fine, so it's definitely not from our side.

**Comment by karalabe** [comment]
Seems gokzg changed their Blobs to be of a different type and did not do a major version bump. That will result in Go thinking it's fine to use the latest version but in reality it is not. https://github.com/crate-crypto/go-kzg-4844/releases/tag/v0.4.0

You'll need to explicitly pin the version used in Geth to downgrade it to the old Blob type def.

**Comment by karalabe** [comment]
The other solution is that we will need to pull in a new dependency to fix the usage in Geth to work according to the new version of gokzg. Unfortunate with the semvers and how Go handles them.

**Comment by karalabe** [comment]
This was reverted upstream, so should be fixed.

**Comment by ThomasP1988** [comment]
Bug came back, I've added this line in go.mod and it works, just to let you know

`replace github.com/crate-crypto/go-kzg-4844 v1.0.0 => github.com/crate-crypto/go-kzg-4844 v0.7.0`

**Comment by adelowo** [comment]
> Bug came back, I've added this line in go.mod and it works, just to let you know
> 
> `replace github.com/crate-crypto/go-kzg-4844 v1.0.0 => github.com/crate-crypto/go-kzg-4844 v0.7.0`

can confirm this works
