### ISSUE TITLE
Problem syncing timed out DAO fork-check, dropping

### ISSUE THREAD

**Issue by pipaman** [ethereum/go-ethereum#2857]
#### System information

Geth version: 1.4.10
OS & Version: Linux Ubuntu 14.04

#### Expected behaviour

Geth working as usual

#### Actual behaviour

I'm getting 'timed out DAO fork-check, dropping' all the time and it doesn't sync as it should. Sometimes, it syncs but then it start failing with this message and now the blockchain is 2,500 blocks ahead the other server I have with the same version of geth running on the same OS.

#### Steps to reproduce the behaviour
geth --rpc --support-dao-fork --rpcaddr 127.0.0.1 console

Thanks on advanced,
P/

**Comment by gituser** [comment]
I'm getting the same issue, but not on all machines.

**Comment by pipaman** [comment]
I have this issue in one machine from 3, all with the same configuration (they are clones). I restarted several times and the issue wasn't fixed. 
Finally, the issue was gone. I hope it doesn't return because a popular wallet depends on this.

**Comment by ShawnKimble** [comment]
Same issue, though a cron job (via python script) creates new problem of sync restart from block 0.   
'timed out DAO fork-check, dropping' rate as of today is much less than 2 days ago, so fingers crossed it completes this time.

**Comment by karalabe** [comment]
The "timed out" log is just a log anomaly (I forgot to top the timer if the peer disconnect before finishing the DAO challenge (e.g. remote side finished challenge and deemed to disconnect)). You can disregard it.

As for getting behind, I did find a bug (it was introduced quite some time ago, back in the EDGE release) that causes bad peers not to be dropped. It can lead to stalls in certain scenarios. This is also fixed on develop.

I'm further writing up two more patches to the downloader to make it less resource intensive and more flexible.

**Comment by stricq** [comment]
Also seeing the timed out messages.  My wallet is falling behind and not picking up transfers from the mining pool.

**Comment by nhq9765** [comment]
Getting all kinds of error since the hard forque. It has never synced since then

invalid receipt root hash
Unhandled trie error missing trie node
peer timed out DAO fork-check dropping

**Comment by gituser** [comment]
is there any update on this one?

it's a critical issue imo

**Comment by ShawnKimble** [comment]
My only solution to this was to make use of a Virtual Server third party instance, as my local connection, IP address or amount of memory were the issue.  A new instance, fresh IP, and plenty of bandwidth and memory seemed to allow me to sync.

**Comment by TOMOAKI12345** [comment]
$ geth --fast console 
and 
$ geth console
then it starts to download blocks.

**Comment by gegemos** [comment]
Same issue, not able to update the chain since the hard fork. 
geth --fast or geth updatedb , generate the same message when getting close to block 1.920.000 DAO fork-check dropping

**Comment by fjl** [comment]
@nhq9765

> invalid receipt root hash
> Unhandled trie error missing trie node

These errors indicate a problem with your database and should be unrelated to the fork.

@gegemos

> geth updatedb

It should not be necessary to run this command.

**Comment by fjl** [comment]
We are looking into this issue.

**Comment by emosto** [comment]
I can confirm the same issue. Trying now with the suggestion of @Lietmotiv

**Comment by pannous** [comment]
Happened here after 10sec  
 v1.4.10 
```
$ geth removedb
Removing chaindata...
Removed in 101.632µs
$ geth --fast --cache=1024 --maxpeers 99 --jitvm --support-dao-fork console 
> I0804 16:21:53.600968 eth/handler.go:295] Peer 6cb867ef9041ffc2 [eth/63]: timed out DAO fork-check, dropping
```

**Comment by fjl** [comment]
Note that the message does not necessarily indicate a problem. Please give it some time to start the sync.

**Comment by azulmarino** [comment]
Any fix yet?

**Comment by azulmarino** [comment]
I0804 18:08:00.198441 eth/downloader/downloader.go:1087] Peer f6f1d91284650 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 1920000

**Comment by pannous** [comment]
@fjl you were right, it was a non-issue here.

**Comment by gegemos** [comment]
tks ! it is working now

**Comment by larrysmith1000** [comment]
Hey All.  I have been trying to figure this out for along time.  I am using windows, and when I synchronize my system clock to time.nist.gov, as described in this article: 
http://www.tenforums.com/tutorials/6410-clock-synchronize-internet-time-server-windows-10-a.html

The problem is fixed.  It then over time will slowly get worse, but if I resync my system clock it works again.

I tested it, and if your system clock is off by +-1 second, then it totally fails.

I bet in the 0.8.1 update, they made the clock sync rules much more strict.  I assume they did this because it makes recursive attacks much more difficult if new pieces of code require time stamps, then the order the code is executed can be verified (given the DAO situation).

**Comment by fjl** [comment]
> I bet in the 0.8.1 update, they made the clock sync rules much more strict.

I can assure you that nothing has changed in this regard.

**Comment by Pnemon** [comment]
I too was getting the same message when I was trying to synch. I first tried synching my clock but that made no difference then I tried @Lietmotiv 's method and now it's working very quickly. 

> `geth removedb `
> 
> ` geth --fast --maxpeers 99 --cache 1024 --jitvm `

If you're getting timed out, try this out because it might work for you like it did for me.

**Comment by gregbkr** [comment]
Hello,
Again same issue today, geth 1.4.10 stopped syncing.
```
August 18th 2016, 04:00:47.000	ethereum	I0818 02:00:47.732758 core/blockchain.go:963] imported 0 block(s) (0 queued 97 ignored) including 0 txs in 826.533488ms. #2060297 [60a75d19 / 716a3563]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.491786 core/blockchain.go:963] imported 0 block(s) (0 queued 2 ignored) including 0 txs in 13.98311ms. #2060162 [0fa77512 / 737ea164]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.892381 core/blockchain.go:963] imported 0 block(s) (0 queued 38 ignored) including 0 txs in 224.434135ms. #2060200 [52fb0be3 / 420bb568]
August 18th 2016, 04:00:46.000	ethereum	I0818 02:00:46.168098 core/blockchain.go:963] imported 0 block(s) (0 queued 3 ignored) including 0 txs in 17.807034ms. #2060160 [b399db4c / 2f267a7b]
August 18th 2016, 04:00:39.000	ethereum	I0818 02:00:39.633898 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 13.45657ms. #2091928 [d8257a94 / d8257a94]

```
I had same issues with version : 146, 148 and recently with 149 cf: https://github.com/ethereum/go-ethereum/issues/2361

Thank you for your help!
Greg.

**Comment by Viking-yu** [comment]
I had same issue since Sept 24, with instance: Geth/v1.4.12-stable/linux/go1.6.2. 

Any Suggestion

**Comment by crossed1000** [comment]
Getting the same issue on linux.

**Comment by karalabe** [comment]
What internet connection do you have?

**Comment by crossed1000** [comment]
What do you mean?
using VPS, 1GPBS uplink
I've got one server running ETC (no problems) and one running ETH which is having issues....tried it on a fresh server all getting the same issues.

**Comment by karalabe** [comment]
The fork check dropping think is mostly a log message, you shouldn't have problems if you have a good network link. Did you upgrade to Geth 1.4.13? It was released today and contains a fix to handle a currently ongoing DoS attack.

**Comment by crossed1000** [comment]
running Geth/1.5.0-unstable/go1.6.2/linux

**Comment by crossed1000** [comment]
Should I downgrade to 1.4.13?

**Comment by karalabe** [comment]
If you are running develop, please pull in the latest code pushed today. Alternatively you can also use cross builds from: https://gitter.im/ethereum/go-ethereum?at=57e920e7ab9ba81255e506af

**Comment by crossed1000** [comment]
how do I do that (sorry for the noob question, not the best with this stuff)

**Comment by karalabe** [comment]
If you are not familiar with building it yourself, just download a binary from the post I linked above.

**Comment by crossed1000** [comment]
im still on Geth/1.5.0-unstable/go1.6.2/linux after pulling and extracting those files
is that ok?

**Comment by crossed1000** [comment]
nope, even worse now, before I could get to 2.3 mil and 1k blocks before full sync it would give me the error.....now I cant get a single block

I0926 14:12:58.140370 eth/downloader/downloader.go:305] Synchronisation failed: state data download canceled (requested)
I0926 14:13:00.624875 eth/handler.go:290] Peer 3064b52be7c469ae [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:15.382023 eth/handler.go:290] Peer cad7474abd50c7a7 [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:20.901423 eth/handler.go:290] Peer c04df9f383e87678 [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:21.510890 eth/handler.go:290] Peer b3c7c534030df4c1 [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:28.647820 eth/handler.go:290] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:33.986943 eth/handler.go:290] Peer 9b034fde747960fe [eth/63]: timed out DAO fork-check, dropping
I0926 14:13:37.725164 eth/downloader/downloader.go:305] Synchronisation failed: block body download canceled (requested)


Can you guide me as to removing my current version of geth and only using 1.4.13?

**Comment by karalabe** [comment]
Please let it run for a bit (i.e. 10 minutes and see if it resolves)

**Comment by crossed1000** [comment]
--fast doesn't work on this version? even with --fast it still uses normal syncing processes.

**Comment by crossed1000** [comment]
it's on around 530k blocks at the moment, we will see if it stops 1k blocks before like previous syncs. I will keep you posted.

**Comment by crossed1000** [comment]
nope
I0926 15:31:43.330112 core/blockchain.go:759] imported 1 receipt(s) (0 ignored) in 882.828µs. #2329456 [86da1b94… / 86da1b94…]
I0926 15:31:43.330231 core/blockchain.go:271] committed block #2329456 [86da1b94…] as new head
I0926 15:31:50.989905 eth/handler.go:290] Peer eae75b6518ea452b [eth/63]: timed out DAO fork-check, dropping
I0926 15:31:51.778807 eth/handler.go:290] Peer 21c130de31db2a6b [eth/63]: timed out DAO fork-check, dropping
I0926 15:32:06.550140 eth/handler.go:290] Peer 9cdd171d8ad51c60 [eth/63]: timed out DAO fork-check, dropping
I0926 15:32:10.919534 eth/handler.go:290] Peer 91585c7c5de829c7 [eth/63]: timed out DAO fork-check, dropping
I0926 15:32:56.733926 eth/handler.go:290] Peer 3f5c32ba5aeb2fde [eth/63]: timed out DAO fork-check, dropping
I0926 15:43:41.634017 eth/handler.go:290] Peer 552022b1501a3aba [eth/63]: timed out DAO fork-check, dropping

**Comment by whappshh** [comment]
Same issue here,windows 7,geth 1.4.13

**Comment by ivands** [comment]
why is this issue closed. it cleary is still a problem

**Comment by crossed1000** [comment]
How I fixed it....
1. Completely remove Geth (backup your keystore file)
2. Upgrade to 1.5.2 (ISSUE IS IN 1.5.0) 
3. Viola...

I upgraded to 1.5.2 and threw on geth --fast --cache=1024 --maxpeers 99 and it synced within 2 hours, and it still working to this day. 

You have to completely remove your old version of geth or update to 1.5.2....as long as you have 1.5.2 it'll work just fine.

**Comment by ivands** [comment]
Why is this issue closed when their clearly still is a problem.
I'm still getting the following messages.

I1003 11:19:51.603087 eth/handler.go:290] Peer 6491824efd666143 [eth/63]: timed out DAO fork-check, dropping
I1003 11:19:53.525213 eth/handler.go:290] Peer 65990d8e0a1b4d63 [eth/63]: timed out DAO fork-check, dropping
I1003 11:20:04.314350 eth/handler.go:290] Peer b3c7c534030df4c1 [eth/63]: timed out DAO fork-check, dropping
I1003 11:20:04.722110 eth/handler.go:290] Peer e67efab25fd366f4 [eth/63]: timed out DAO fork-check, dropping
I1003 11:20:23.056053 eth/handler.go:290] Peer 3064b52be7c469ae [eth/63]: timed out DAO fork-check, dropping

This is a real problem because the blockchain will stop syncing and only receive does error messages after a while.
Almost every 2 days i have to delete the blockchain and redownload it.
Also sending transaction doesn't work when the blockchain is out of sync apparently.
Our customers are really getting annoyed for not receiving they ethers.
Could you guys please take this issue more seriously.
It's really annoying seeing this issue closed when its clearly not resolved.

**Comment by xPakrikx** [comment]
Why is this closed ... i have same problem under geth 1.4.15. So it's not solved. 
Same problem under Windows and Linux

**Comment by karalabe** [comment]
Because this issue has zero to do with the current problem, which is a DoS attack. As said over a ton of threads, please wait for a fix. And please don't bloat closed issues. If you feel there's something wrong, open a new issue.

**Comment by Lietmotiv** [comment]
@xPakrikx Please try this:

0. Backup your wallet.
1. Download the latest Geth
2. Make sure your time is synced to a time service of your choosing.
3. ./geth removedb
4. ./geth --fast --maxpeers 99 --cache 1024 --jitvm

**Comment by ronakthamor** [comment]
I have the same problem with version 1.5.0
