### ISSUE TITLE
Chain rollback fault injection caused node crash

### ISSUE THREAD

**Issue by 1033309821** [ethereum/go-ethereum#33396]
We are conducting a security test on the Ethereum network using fuzzing and fault injection. The following findings were made while constructing fault injection experiments specific to the blockchain (using set_head for rollback or fork).

**Key Findings:**

1. We also conducted the same tests on Besu (which also supports `set_head`). Besu's block rollback speed was very fast, and no anomalies or bugs occurred.  ——**Part 1**
2. Rollback on geth was very slow, and there was a high probability that the node would get crash midway through execution.  **——Part 2**

### Part 1. The Besu client worked flawlessly and synced quickly. Screenshots and logs of the Besu client experiment are shown below:
```
fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1"],"id":1}' http://127.0.0.1:32888 | jq

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "Success"
}
fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32888 12                
1) RPC reachable & client version
RPC reachable. clientVersion: besu/v25.10.0/linux-x86_64/openjdk-java-21
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 1 (hex:0x1)
Waiting 12s to check progress...
Block progressed: 1 -> 6461 (+6460)
4) recent block transactions check
Transactions in latest block: 0
Latest block has no transactions.
5) txpool status (if supported)
txpool_status:
null
6) peer count
Peer count: 4
````

### Part 2. Geth client experimental logs (in case of node crash):
```
fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12
1) RPC reachable & client version
RPC reachable. clientVersion: Geth/v1.16.7-unstable-5b77af39-20251103/linux-amd64/go1.24.9
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 6471 (hex:0x1947)
Waiting 12s to check progress...
Block progressed: 6471 -> 6472 (+1)

fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1900"],"id":1}' http://127.0.0.1:32883 | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}

fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12                
1) RPC reachable & client version
RPC reachable. clientVersion: Geth/v1.16.7-unstable-5b77af39-20251103/linux-amd64/go1.24.9
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 6400 (hex:0x1900)
Waiting 12s to check progress...
Block progressed: 6400 -> 6474 (+74)
4) recent block transactions check
Transactions in latest block: 0
Latest block has no transactions.
5) txpool status (if supported)
txpool_status:
{
  "pending": "0x0",
  "queued": "0x0"
}
6) peer count
Peer count: 4
fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1"],"id":1}' http://127.0.0.1:32883 | jq 


fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12                
1) RPC reachable & client version
[FAIL] Cannot reach RPC at 127.0.0.1:32883
```

#### Client error message logs:
```
[el-1-geth-lighthouse] INFO [11-05|09:45:27.990] Truncating from head                     type=state ohead=5303 tail=0 nhead=5302
[el-1-geth-lighthouse] INFO [11-05|09:45:28.014] Rewound to block with state              number=5301 hash=9bcb68..2b10b8
[el-1-geth-lighthouse] INFO [11-05|09:45:28.015] Truncating from head                     type=state ohead=5302 tail=0 nhead=5301
[el-1-geth-lighthouse] INFO [11-05|09:45:28.045] Rewound to block with state              number=5300 hash=e579e0..ec7ad8
[el-1-geth-lighthouse] INFO [11-05|09:45:28.046] Truncating from head                     type=state ohead=5301 tail=0 nhead=5300
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] WARN [11-05|09:45:28.047] Ignoring payload while snap syncing      number=6479 hash=4e0d9b..32bf65 reason="chain gapped, head: 6474, newHead: 6479"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Forkchoice requested sync to new head    number=6479 hash=4e0d9b..32bf65 finalized=unknown
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Restarting sync cycle                    reason="chain gapped, head: 6474, newHead: 6479"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.069] Syncing beacon headers                   downloaded=74 left=0 eta=0s
[el-1-geth-lighthouse] ERROR[11-05|09:45:28.070] Failed to clean stale beacon headers     err="filled header below beacon header tail: 6474 < 6478"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.075] Rewound to block with state              number=5299 hash=6fcc2f..52f458
[el-1-geth-lighthouse] CRIT [11-05|09:45:28.075] Chain is stateless at a non-genesis block
```

### Env
We use kurtosis's ethereum-package for testing, and the relevant configuration is as follows:
````
// The ethereum-package network-para.yaml
participants:
  - el_type: geth V1.16.2
    cl_type: lighthouse V7.0.1
  - el_type: nethermind V1.33.0
    cl_type: lighthouse V7.0.1
  - el_type: reth V1.6.0
    cl_type: lighthouse V7.0.1
  - el_type: besu V25.8.0
    cl_type: lighthouse V7.0.1
  - el_type: erigon V3.0.15
    cl_type: lighthouse V7.0.1
additional_services:
  - dora
```

**Comment by jsvisa** [comment]
I think https://github.com/ethereum/go-ethereum/pull/32139 will fix this one

**Comment by rjl493456442** [comment]
Can you please try the latest master branch? We have improved the sync mode management a little bit.

**Comment by rjl493456442** [comment]
But it's definitely a valuable edge case that we should investigate.

**Comment by 1033309821** [comment]
Hey @rjl493456442 ,
I just tried the current geth master branch, and the crash still occurs. The logs are as follows:
```
[el-01-geth-lighthouse] INFO [12-13|04:36:05.989] Rewound to block with state              number=26  hash=70c181..37f4d2
[el-01-geth-lighthouse] INFO [12-13|04:36:05.991] Truncating from head                     type=state ohead=27 tail=0 nhead=26
[el-01-geth-lighthouse] INFO [12-13|04:36:06.006] Rewound to block with state              number=25  hash=8555d0..239af0
[el-01-geth-lighthouse] INFO [12-13|04:36:06.009] Truncating from head                     type=state ohead=26 tail=0 nhead=25
[el-01-geth-lighthouse] INFO [12-13|04:36:06.030] Rewound to block with state              number=24  hash=2fe0f2..17d42a
[el-01-geth-lighthouse] INFO [12-13|04:36:06.032] Truncating from head                     type=state ohead=25 tail=0 nhead=24
[el-01-geth-lighthouse] INFO [12-13|04:36:06.048] Rewound to block with state              number=23  hash=271701..a8a55f
[el-01-geth-lighthouse] INFO [12-13|04:36:06.053] Truncating from head                     type=state ohead=24 tail=0 nhead=23
[el-01-geth-lighthouse] INFO [12-13|04:36:06.073] Rewound to block with state              number=22  hash=1d9e73..bd9437
[el-01-geth-lighthouse] INFO [12-13|04:36:06.076] Truncating from head                     type=state ohead=23 tail=0 nhead=22
[el-01-geth-lighthouse] INFO [12-13|04:36:06.093] Rewound to block with state              number=21  hash=ea2419..afc468
[el-01-geth-lighthouse] INFO [12-13|04:36:06.095] Truncating from head                     type=state ohead=22 tail=0 nhead=21
[el-01-geth-lighthouse] INFO [12-13|04:36:06.114] Rewound to block with state              number=20  hash=94c6ec..ffbf9e
[el-01-geth-lighthouse] INFO [12-13|04:36:06.115] Truncating from head                     type=state ohead=21 tail=0 nhead=20
[el-01-geth-lighthouse] INFO [12-13|04:36:06.122] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] INFO [12-13|04:36:06.122] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] WARN [12-13|04:36:06.122] Ignoring payload while snap syncing      number=187 hash=cc6237..d496d3 reason="forced head needed for startup"
[el-01-geth-lighthouse] INFO [12-13|04:36:06.133] Rewound to block with state              number=19  hash=257de0..dc2d48
[el-01-geth-lighthouse] INFO [12-13|04:36:06.135] Truncating from head                     type=state ohead=20 tail=0 nhead=19
[el-01-geth-lighthouse] INFO [12-13|04:36:06.149] Forkchoice requested sync to new head    number=187 hash=cc6237..d496d3 finalized=unknown
[el-01-geth-lighthouse] INFO [12-13|04:36:06.149] Block synchronisation started
[el-01-geth-lighthouse] INFO [12-13|04:36:06.149] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] INFO [12-13|04:36:06.158] Rewound to block with state              number=18  hash=c08e9a..16530a
[el-01-geth-lighthouse] INFO [12-13|04:36:06.158] Disabled trie database due to state sync
[el-01-geth-lighthouse] INFO [12-13|04:36:06.158] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] CRIT [12-13|04:36:06.158] Failed to rollback state                 err="waiting for sync"
```

**Comment by rjl493456442** [comment]
Thanks for the report, we will prioritize the issue!

**Comment by rjl493456442** [comment]
@1033309821 can you please try out this fix in your setup? https://github.com/ethereum/go-ethereum/pull/33428

**Comment by 1033309821** [comment]
@rjl493456442 
Of course, I'd be happy to help you with the fix testing. It's clear that the nodes in this PR are no longer crash.
However, they still get stuck. Here is the Geth log:

```
// RPC response
curl -s -X POST -H "Content-Type: application/json" \ 
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1"],"id":1}' http://127.0.0.1:33072  | jq  
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "not allowed to rewind to a future block"
  }
}

// Log
[el-01-geth-lighthouse] INFO [12-16|10:09:27.057] Rewound to block with state              number=47  hash=2ab725..b76b85
[el-01-geth-lighthouse] INFO [12-16|10:09:27.061] Truncating from head                     type=state ohead=48  tail=0 nhead=47
[el-01-geth-lighthouse] INFO [12-16|10:09:27.076] Rewound to block with state              number=46  hash=beb407..d489e5
[el-01-geth-lighthouse] INFO [12-16|10:09:27.078] Truncating from head                     type=state ohead=47  tail=0 nhead=46
[el-01-geth-lighthouse] INFO [12-16|10:09:27.092] Rewound to block with state              number=45  hash=96c487..9c68d7
[el-01-geth-lighthouse] INFO [12-16|10:09:27.095] Truncating from head                     type=state ohead=46  tail=0 nhead=45
[el-01-geth-lighthouse] INFO [12-16|10:09:27.113] Rewound to block with state              number=44  hash=97101a..fab8ef
[el-01-geth-lighthouse] INFO [12-16|10:09:27.115] Truncating from head                     type=state ohead=45  tail=0 nhead=44
[el-01-geth-lighthouse] INFO [12-16|10:09:27.132] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] INFO [12-16|10:09:27.135] Rewound to block with state              number=43  hash=610fb8..e6bdbc
[el-01-geth-lighthouse] INFO [12-16|10:09:27.137] Truncating from head                     type=state ohead=44  tail=0 nhead=43
[el-01-geth-lighthouse] INFO [12-16|10:09:27.154] Rewound to block with state              number=42  hash=619931..5e48f0
[el-01-geth-lighthouse] INFO [12-16|10:09:27.156] Truncating from head                     type=state ohead=43  tail=0 nhead=42
[el-01-geth-lighthouse] INFO [12-16|10:09:27.162] Forkchoice requested sync to new head    number=411 hash=b25867..76faad finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:09:27.176] Rewound to block with state              number=41  hash=020ee7..8a0dd5
[el-01-geth-lighthouse] INFO [12-16|10:09:27.178] Truncating from head                     type=state ohead=42  tail=0 nhead=41
[el-01-geth-lighthouse] INFO [12-16|10:09:27.199] Rewound to block with state              number=40  hash=7881b7..75c28a
[el-01-geth-lighthouse] INFO [12-16|10:09:27.201] Truncating from head                     type=state ohead=41  tail=0 nhead=40
[el-01-geth-lighthouse] INFO [12-16|10:09:27.216] Rewound to block with state              number=39  hash=3d30eb..0c4d61
[el-01-geth-lighthouse] INFO [12-16|10:09:27.220] Truncating from head                     type=state ohead=40  tail=0 nhead=39
[el-01-geth-lighthouse] INFO [12-16|10:09:27.234] Rewound to block with state              number=38  hash=d3e729..ec4621
[el-01-geth-lighthouse] INFO [12-16|10:09:27.236] Truncating from head                     type=state ohead=39  tail=0 nhead=38
[el-01-geth-lighthouse] INFO [12-16|10:09:27.253] Rewound to block with state              number=37  hash=b85c0f..cdfd8e
[el-01-geth-lighthouse] INFO [12-16|10:09:27.255] Truncating from head                     type=state ohead=38  tail=0 nhead=37
[el-01-geth-lighthouse] INFO [12-16|10:09:27.271] Rewound to block with state              number=36  hash=4b3a8a..e2b642
[el-01-geth-lighthouse] INFO [12-16|10:09:27.273] Truncating from head                     type=state ohead=37  tail=0 nhead=36
[el-01-geth-lighthouse] INFO [12-16|10:09:27.288] Rewound to block with state              number=35  hash=40b64f..65aab0
[el-01-geth-lighthouse] INFO [12-16|10:09:27.289] Truncating from head                     type=state ohead=36  tail=0 nhead=35
[el-01-geth-lighthouse] INFO [12-16|10:09:27.303] Rewound to block with state              number=34  hash=1bd069..96d6fa
[el-01-geth-lighthouse] INFO [12-16|10:09:27.304] Truncating from head                     type=state ohead=35  tail=0 nhead=34
[el-01-geth-lighthouse] INFO [12-16|10:09:27.318] Rewound to block with state              number=33  hash=740196..be74f0
[el-01-geth-lighthouse] INFO [12-16|10:09:27.319] Truncating from head                     type=state ohead=34  tail=0 nhead=33
[el-01-geth-lighthouse] INFO [12-16|10:09:27.333] Rewound to block with state              number=32  hash=97d172..83b368
[el-01-geth-lighthouse] INFO [12-16|10:09:27.334] Truncating from head                     type=state ohead=33  tail=0 nhead=32
[el-01-geth-lighthouse] INFO [12-16|10:09:27.348] Rewound to block with state              number=31  hash=f0a113..248220
[el-01-geth-lighthouse] INFO [12-16|10:09:27.350] Truncating from head                     type=state ohead=32  tail=0 nhead=31
[el-01-geth-lighthouse] INFO [12-16|10:09:27.363] Rewound to block with state              number=30  hash=b0f593..b84387
[el-01-geth-lighthouse] INFO [12-16|10:09:27.365] Truncating from head                     type=state ohead=31  tail=0 nhead=30
[el-01-geth-lighthouse] INFO [12-16|10:09:27.379] Rewound to block with state              number=29  hash=45e94e..f9efe9
[el-01-geth-lighthouse] INFO [12-16|10:09:27.380] Truncating from head                     type=state ohead=30  tail=0 nhead=29
[el-01-geth-lighthouse] INFO [12-16|10:09:27.394] Rewound to block with state              number=28  hash=e78979..19c668
[el-01-geth-lighthouse] INFO [12-16|10:09:27.396] Truncating from head                     type=state ohead=29  tail=0 nhead=28
[el-01-geth-lighthouse] INFO [12-16|10:09:27.410] Rewound to block with state              number=27  hash=5c1e4f..ed9ad0
[el-01-geth-lighthouse] INFO [12-16|10:09:27.412] Truncating from head                     type=state ohead=28  tail=0 nhead=27
[el-01-geth-lighthouse] INFO [12-16|10:09:27.425] Rewound to block with state              number=26  hash=58485b..bc531f
[el-01-geth-lighthouse] INFO [12-16|10:09:27.427] Truncating from head                     type=state ohead=27  tail=0 nhead=26
[el-01-geth-lighthouse] INFO [12-16|10:09:27.440] Rewound to block with state              number=25  hash=aad1a8..6031bc
[el-01-geth-lighthouse] INFO [12-16|10:09:27.442] Truncating from head                     type=state ohead=26  tail=0 nhead=25
[el-01-geth-lighthouse] INFO [12-16|10:09:27.455] Rewound to block with state              number=24  hash=da2ed8..700994
[el-01-geth-lighthouse] INFO [12-16|10:09:27.457] Truncating from head                     type=state ohead=25  tail=0 nhead=24
[el-01-geth-lighthouse] INFO [12-16|10:09:27.470] Rewound to block with state              number=23  hash=1da017..9a1bf5
[el-01-geth-lighthouse] INFO [12-16|10:09:27.471] Truncating from head                     type=state ohead=24  tail=0 nhead=23
[el-01-geth-lighthouse] INFO [12-16|10:09:27.485] Rewound to block with state              number=22  hash=c6692d..e55392
[el-01-geth-lighthouse] INFO [12-16|10:09:27.486] Truncating from head                     type=state ohead=23  tail=0 nhead=22
[el-01-geth-lighthouse] INFO [12-16|10:09:27.500] Rewound to block with state              number=21  hash=b4f582..7d9666
[el-01-geth-lighthouse] INFO [12-16|10:09:27.501] Truncating from head                     type=state ohead=22  tail=0 nhead=21
[el-01-geth-lighthouse] INFO [12-16|10:09:27.515] Rewound to block with state              number=20  hash=372438..50866f
[el-01-geth-lighthouse] INFO [12-16|10:09:27.516] Truncating from head                     type=state ohead=21  tail=0 nhead=20
[el-01-geth-lighthouse] INFO [12-16|10:09:27.530] Rewound to block with state              number=19  hash=2819e6..733057
[el-01-geth-lighthouse] INFO [12-16|10:09:27.531] Truncating from head                     type=state ohead=20  tail=0 nhead=19
[el-01-geth-lighthouse] INFO [12-16|10:09:27.545] Rewound to block with state              number=18  hash=392862..459af9
[el-01-geth-lighthouse] INFO [12-16|10:09:27.547] Truncating from head                     type=state ohead=19  tail=0 nhead=18
[el-01-geth-lighthouse] INFO [12-16|10:09:27.560] Rewound to block with state              number=17  hash=2f0143..888aae
[el-01-geth-lighthouse] INFO [12-16|10:09:27.562] Truncating from head                     type=state ohead=18  tail=0 nhead=17
[el-01-geth-lighthouse] INFO [12-16|10:09:27.576] Rewound to block with state              number=16  hash=1e5d86..533b58
[el-01-geth-lighthouse] INFO [12-16|10:09:27.578] Truncating from head                     type=state ohead=17  tail=0 nhead=16
[el-01-geth-lighthouse] INFO [12-16|10:09:27.591] Rewound to block with state              number=15  hash=6fb2b2..2d9915
[el-01-geth-lighthouse] INFO [12-16|10:09:27.593] Truncating from head                     type=state ohead=16  tail=0 nhead=15
[el-01-geth-lighthouse] INFO [12-16|10:09:27.606] Rewound to block with state              number=14  hash=42cc85..c1f1f4
[el-01-geth-lighthouse] INFO [12-16|10:09:27.608] Truncating from head                     type=state ohead=15  tail=0 nhead=14
[el-01-geth-lighthouse] INFO [12-16|10:09:27.622] Rewound to block with state              number=13  hash=8b5486..c6b9ca
[el-01-geth-lighthouse] INFO [12-16|10:09:27.624] Truncating from head                     type=state ohead=14  tail=0 nhead=13
[el-01-geth-lighthouse] INFO [12-16|10:09:27.637] Rewound to block with state              number=12  hash=5ed3d7..165eab
[el-01-geth-lighthouse] INFO [12-16|10:09:27.639] Truncating from head                     type=state ohead=13  tail=0 nhead=12
[el-01-geth-lighthouse] INFO [12-16|10:09:27.652] Rewound to block with state              number=11  hash=58d683..513e64
[el-01-geth-lighthouse] INFO [12-16|10:09:27.654] Truncating from head                     type=state ohead=12  tail=0 nhead=11
[el-01-geth-lighthouse] INFO [12-16|10:09:27.667] Rewound to block with state              number=10  hash=93f1ce..10172c
[el-01-geth-lighthouse] INFO [12-16|10:09:27.669] Truncating from head                     type=state ohead=11  tail=0 nhead=10
[el-01-geth-lighthouse] INFO [12-16|10:09:27.683] Rewound to block with state              number=9   hash=540c40..27d616
[el-01-geth-lighthouse] INFO [12-16|10:09:27.685] Truncating from head                     type=state ohead=10  tail=0 nhead=9
[el-01-geth-lighthouse] INFO [12-16|10:09:27.700] Rewound to block with state              number=8   hash=8b199b..8df697
[el-01-geth-lighthouse] INFO [12-16|10:09:27.701] Truncating from head                     type=state ohead=9   tail=0 nhead=8
[el-01-geth-lighthouse] INFO [12-16|10:09:27.715] Rewound to block with state              number=7   hash=cd9d2f..2703fc
[el-01-geth-lighthouse] INFO [12-16|10:09:27.717] Truncating from head                     type=state ohead=8   tail=0 nhead=7
[el-01-geth-lighthouse] INFO [12-16|10:09:27.731] Rewound to block with state              number=6   hash=baadfd..6c69f3
[el-01-geth-lighthouse] INFO [12-16|10:09:27.733] Truncating from head                     type=state ohead=7   tail=0 nhead=6
[el-01-geth-lighthouse] INFO [12-16|10:09:27.746] Rewound to block with state              number=5   hash=a64719..f461eb
[el-01-geth-lighthouse] INFO [12-16|10:09:27.748] Truncating from head                     type=state ohead=6   tail=0 nhead=5
[el-01-geth-lighthouse] INFO [12-16|10:09:27.761] Rewound to block with state              number=4   hash=d274d3..cf626a
[el-01-geth-lighthouse] INFO [12-16|10:09:27.763] Truncating from head                     type=state ohead=5   tail=0 nhead=4
[el-01-geth-lighthouse] INFO [12-16|10:09:27.777] Rewound to block with state              number=3   hash=e8bb6c..1f644f
[el-01-geth-lighthouse] INFO [12-16|10:09:27.778] Truncating from head                     type=state ohead=4   tail=0 nhead=3
[el-01-geth-lighthouse] INFO [12-16|10:09:27.792] Rewound to block with state              number=2   hash=2d93ec..11bf96
[el-01-geth-lighthouse] INFO [12-16|10:09:27.793] Truncating from head                     type=state ohead=3   tail=0 nhead=2
[el-01-geth-lighthouse] INFO [12-16|10:09:27.807] Rewound to block with state              number=1   hash=f185b6..3e7be4
[el-01-geth-lighthouse] WARN [12-16|10:09:27.809] Truncating freezer table                 database=/data/geth/execution-data/geth/chaindata/ancient/chain table=receipts items=257 limit=2
[el-01-geth-lighthouse] WARN [12-16|10:09:27.813] Truncating freezer table                 database=/data/geth/execution-data/geth/chaindata/ancient/chain table=headers items=257 limit=2
[el-01-geth-lighthouse] WARN [12-16|10:09:27.817] Truncating freezer table                 database=/data/geth/execution-data/geth/chaindata/ancient/chain table=hashes items=257 limit=2
[el-01-geth-lighthouse] WARN [12-16|10:09:27.821] Truncating freezer table                 database=/data/geth/execution-data/geth/chaindata/ancient/chain table=bodies items=257 limit=2
[el-01-geth-lighthouse] INFO [12-16|10:09:27.825] Loaded most recent local block           number=1   hash=f185b6..3e7be4 age=1h22m
[el-01-geth-lighthouse] INFO [12-16|10:09:27.825] Disabled trie database due to state sync
[el-01-geth-lighthouse] ERROR[12-16|10:09:27.825] Failed to reset txpool state             err="missing trie node 035dcb0eee64750e07a2ae4e04d646db903f5b74774bf8d230c66c156c875cbf (path ) layer stale"
[el-01-geth-lighthouse] ERROR[12-16|10:09:27.825] Failed to reset txpool state             err="missing trie node 035dcb0eee64750e07a2ae4e04d646db903f5b74774bf8d230c66c156c875cbf (path ) layer stale"
[el-01-geth-lighthouse] ERROR[12-16|10:09:27.825] Failed to reset blobpool state           err="missing trie node 035dcb0eee64750e07a2ae4e04d646db903f5b74774bf8d230c66c156c875cbf (path ) layer stale"
[el-01-geth-lighthouse] INFO [12-16|10:09:27.826] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:27.826] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] ERROR[12-16|10:09:27.826] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:09:32.193] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:09:39.114] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.114] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.114] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:09:39.114] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.114] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:09:39.135] Forkchoice requested sync to new head    number=412 hash=7c68e8..f1635e finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:09:39.135] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.135] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.135] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:09:39.135] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:39.135] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:09:42.206] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:09:51.137] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.137] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.137] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:09:51.139] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.139] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:09:51.158] Forkchoice requested sync to new head    number=413 hash=15a0be..144f2c finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:09:51.158] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.158] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.170] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:09:51.170] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:09:51.171] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:09:52.222] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:02.235] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:03.123] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.124] Reject duplicated disable operation
[el-01-geth-lighthouse] INFO [12-16|10:10:03.124] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.124] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.125] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:03.134] Forkchoice requested sync to new head    number=414 hash=1fb580..abf9eb finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:03.135] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.135] Reject duplicated disable operation
[el-01-geth-lighthouse] INFO [12-16|10:10:03.135] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.135] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] ERROR[12-16|10:10:03.135] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:12.251] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:15.176] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.176] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.176] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:15.176] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.176] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:15.193] Forkchoice requested sync to new head    number=415 hash=ce0ec8..c8cd3f finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:15.193] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.193] Reject duplicated disable operation
[el-01-geth-lighthouse] INFO [12-16|10:10:15.193] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.194] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] ERROR[12-16|10:10:15.194] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:22.264] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:26.501] Forkchoice requested sync to new head    number=415 hash=ce0ec8..c8cd3f finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:26.501] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:26.501] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:26.501] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:26.501] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:26.502] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:27.178] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.182] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.182] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:27.182] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.182] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:27.263] Forkchoice requested sync to new head    number=416 hash=5b4798..94e6bf finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:27.263] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.263] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.263] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:27.263] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:27.263] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:32.280] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:39.172] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.173] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.173] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:39.173] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.174] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:39.184] Forkchoice requested sync to new head    number=417 hash=2d23b3..cdbd69 finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:39.184] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.184] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.184] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:39.184] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:39.184] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:42.294] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:10:51.137] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.138] Reject duplicated disable operation
[el-01-geth-lighthouse] INFO [12-16|10:10:51.138] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.138] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.138] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:51.149] Forkchoice requested sync to new head    number=418 hash=62b377..566193 finalized=unknown
[el-01-geth-lighthouse] INFO [12-16|10:10:51.150] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.150] Reject duplicated disable operation
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.150] Beacon sync linkup unavailable           number=256 hash=a243ac..9be29f
[el-01-geth-lighthouse] INFO [12-16|10:10:51.150] Reenabled snap-sync as chain is stateless
[el-01-geth-lighthouse] ERROR[12-16|10:10:51.150] Beacon backfilling failed                err="beacon linkup unavailable locally: 256 [a243ac7d1982e312cb260dc054038db9a4018c9a7225214a2c1357468c9be29f]"
[el-01-geth-lighthouse] INFO [12-16|10:10:52.310] Looking for peers                        peercount=10 tried=0 static=0
[el-01-geth-lighthouse] INFO [12-16|10:11:02.323] Looking for peers                        peercount=10 tried=0 static=0
```

**Comment by rjl493456442** [comment]
I have updated the branch, please try again.

**Comment by 1033309821** [comment]
@rjl493456442 
Thank you very much for your feedback. I just tested it, and I'm still experiencing the same problem as before. I think the main issue might be elsewhere.
A single call to the `set_head` method currently doesn't cause crashes or getting stuck.
However, if `set_head` is used twice in quick succession, it will cause a stuck error.
For example, if I first roll back the node to 0x50, and then quickly roll back to 0x01, the node will get stuck.

The log is as follows:
```
[el-01-geth-lighthouse] INFO [12-17|06:20:12.906] Syncing beacon headers downloaded=5,216,677 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.909] Syncing beacon headers downloaded=5,216,905 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.913] Syncing beacon headers downloaded=5,217,133 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.917] Syncing beacon headers downloaded=5,217,361 left=0eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.920] Syncing beacon headers downloaded=5,217,589 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.923] Syncing beacon headers downloaded=5,217,817 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.928] Syncing beacon headers downloaded=5,218,045 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.931] Syncing beacon headers downloaded=5,218,273 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.934] Syncing beacon headers downloaded=5,218,501 left=0 eta=0s
[el-01-geth-lighthouse] INFO [12-17|06:20:12.939] Syncing beacon headers downloaded=5,218,729 left=0 eta=0s
```

**Comment by rjl493456442** [comment]
Can you provide a bit more context or logs? I need that information to figure out which part is stuck.

**Comment by 1033309821** [comment]
@rjl493456442 
Sure! The following are the Geth logs corresponding to my two consecutive operations using `set_head` to roll back to `0x10` and `0x01` respectively. 
It is clear that a **chain gapped** event occurred after the rollback was completed.

```
INFO [12-17|08:36:44.140] Imported new potential chain segment     number=34 hash=c55217..2bec4f blocks=1  txs=0 mgas=0.000 elapsed="606.623µs" mgasps=0.000 triediffs=134.80KiB triedirty=0.00B
INFO [12-17|08:36:44.160] Chain head was updated                   number=34 hash=c55217..2bec4f root=197c85..19608a elapsed="54.094µs"
WARN [12-17|08:36:44.161] Nil finalized block cannot evict old blobs
INFO [12-17|08:36:53.394] Looking for peers                        peercount=10 tried=0 static=0
INFO [12-17|08:36:56.127] Imported new potential chain segment     number=35 hash=b109f0..0f1546 blocks=1  txs=0 mgas=0.000 elapsed="640.362µs" mgasps=0.000 triediffs=138.95KiB triedirty=0.00B
INFO [12-17|08:36:56.137] Chain head was updated                   number=35 hash=b109f0..0f1546 root=eb86a2..0a869b elapsed="47.352µs"
WARN [12-17|08:36:56.157] Nil finalized block cannot evict old blobs
WARN [12-17|08:37:01.992] Rewinding blockchain to block            target=16
INFO [12-17|08:37:01.994] Rewound to block with state              number=34 hash=c55217..2bec4f
INFO [12-17|08:37:01.994] Rewound to block with state              number=33 hash=84bb70..83a0b7
INFO [12-17|08:37:01.994] Rewound to block with state              number=32 hash=7e7766..c928cb
INFO [12-17|08:37:01.994] Rewound to block with state              number=31 hash=f29324..56fe95
INFO [12-17|08:37:01.994] Rewound to block with state              number=30 hash=987a77..9a2180
INFO [12-17|08:37:01.994] Rewound to block with state              number=29 hash=094815..668bed
INFO [12-17|08:37:01.995] Rewound to block with state              number=28 hash=9246ae..a2cc16
INFO [12-17|08:37:01.995] Rewound to block with state              number=27 hash=03a6bc..a60a52
INFO [12-17|08:37:01.995] Rewound to block with state              number=26 hash=cc99c0..34fb4c
INFO [12-17|08:37:01.995] Rewound to block with state              number=25 hash=b5fec6..8500c1
INFO [12-17|08:37:01.995] Rewound to block with state              number=24 hash=642b16..cef97f
INFO [12-17|08:37:01.995] Rewound to block with state              number=23 hash=dd6142..40b4c2
INFO [12-17|08:37:01.995] Rewound to block with state              number=22 hash=877ea7..d77192
INFO [12-17|08:37:01.995] Rewound to block with state              number=21 hash=adca75..9323bc
INFO [12-17|08:37:01.995] Rewound to block with state              number=20 hash=9dc104..7e45c4
INFO [12-17|08:37:01.995] Rewound to block with state              number=19 hash=94188e..778d4f
INFO [12-17|08:37:01.996] Rewound to block with state              number=18 hash=9f6abb..167aae
INFO [12-17|08:37:01.996] Rewound to block with state              number=17 hash=7acc93..35a24a
INFO [12-17|08:37:01.996] Rewound to block with state              number=16 hash=e7a8aa..0c5715
INFO [12-17|08:37:01.999] Loaded most recent local block           number=16 hash=e7a8aa..0c5715 age=3m53s
WARN [12-17|08:37:02.000] Nil finalized block cannot evict old blobs
INFO [12-17|08:37:03.407] Looking for peers                        peercount=10 tried=0 static=0
WARN [12-17|08:37:04.954] Rewinding blockchain to block            target=1
INFO [12-17|08:37:04.954] Rewound to block with state              number=15 hash=138750..9c686e
INFO [12-17|08:37:04.954] Rewound to block with state              number=14 hash=de254a..1d983a
INFO [12-17|08:37:04.954] Rewound to block with state              number=13 hash=2f4c3b..3f36e3
INFO [12-17|08:37:04.954] Rewound to block with state              number=12 hash=b62e77..9073e6
INFO [12-17|08:37:04.954] Rewound to block with state              number=11 hash=5f9299..778a25
INFO [12-17|08:37:04.954] Rewound to block with state              number=10 hash=671452..c19c2d
INFO [12-17|08:37:04.954] Rewound to block with state              number=9  hash=a6656b..83dbab
INFO [12-17|08:37:04.954] Rewound to block with state              number=8  hash=4155fa..ac7649
INFO [12-17|08:37:04.955] Rewound to block with state              number=7  hash=691807..454031
INFO [12-17|08:37:04.955] Rewound to block with state              number=6  hash=88cb4a..1a63ea
INFO [12-17|08:37:04.955] Rewound to block with state              number=5  hash=4c5f92..bf052e
INFO [12-17|08:37:04.955] Rewound to block with state              number=4  hash=338112..1d69cb
INFO [12-17|08:37:04.955] Rewound to block with state              number=3  hash=4b34f5..ee06e8
INFO [12-17|08:37:04.955] Rewound to block with state              number=2  hash=cbbffd..251b21
INFO [12-17|08:37:04.955] Rewound to block with state              number=1  hash=748a55..c39422
INFO [12-17|08:37:04.957] Loaded most recent local block           number=1  hash=748a55..c39422 age=6m56s
WARN [12-17|08:37:04.957] Nil finalized block cannot evict old blobs
WARN [12-17|08:37:07.219] Served debug_setHead                     conn=172.16.0.6:34854 reqid=1 duration="42.621µs" err="not allowed to rewind to a future block"
WARN [12-17|08:37:08.109] Ignoring payload with missing parent     number=36 hash=42089f..7138f2 parent=b109f0..0f1546 reason="chain gapped, head: 29, newHead: 36"
INFO [12-17|08:37:08.122] Forkchoice requested sync to new head    number=36 hash=42089f..7138f2
INFO [12-17|08:37:08.122] Restarting sync cycle                    reason="chain gapped, head: 29, newHead: 36"
INFO [12-17|08:37:08.127] Syncing beacon headers                   downloaded=61 left=0 eta=0s
INFO [12-17|08:37:08.135] Syncing beacon headers                   downloaded=89 left=0 eta=0s
INFO [12-17|08:37:08.152] Syncing beacon headers                   downloaded=117 left=0 eta=0s
INFO [12-17|08:37:08.153] Syncing beacon headers                   downloaded=145 left=0 eta=0s
INFO [12-17|08:37:08.164] Syncing beacon headers                   downloaded=173 left=0 eta=0s
INFO [12-17|08:37:08.165] Syncing beacon headers                   downloaded=201 left=0 eta=0s
INFO [12-17|08:37:08.168] Syncing beacon headers                   downloaded=229 left=0 eta=0s
......
// already stuck！！！！
```

**Comment by rjl493456442** [comment]
@1033309821 I have identified there is another bug around and it was triggered in your setup.

I would go with my fix for this ticket first and will work on another fix then.

**Comment by 1033309821** [comment]
> [@1033309821](https://github.com/1033309821) I have identified there is another bug around and it was triggered in your setup.
> 
> I would go with my fix for this ticket first and will work on another fix then.

Hi @rjl493456442,
Therefore, is this testing valid? Can it retrieve bug bounties(Is it serious, or is it considered low)?
