### ISSUE TITLE
personal_unlockAccount

### ISSUE THREAD

**Issue by hht0423** [ethereum/go-ethereum#3473]
#### System information

Geth version: 1.5.4-stable
OS & Version: windows8

#### Expected behaviour
unlock     Account

#### Actual behaviour
no key for given address or file
#### Backtrace

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/MyPC/.m2/repository/ch/qos/logback/logback-classic/1.1.8/logback-classic-1.1.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/MyPC/.m2/repository/org/slf4j/slf4j-log4j12/1.7.12/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2016/12/20 14:57:28:347 CST [DEBUG] wire - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2016/12/20 14:57:28:352 CST [DEBUG] wire - http-outgoing-0 >> "Content-Type: application/json; charset=UTF-8[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "Content-Length: 129[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "Host: localhost:8545[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_112)[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "[\r][\n]"
2016/12/20 14:57:28:353 CST [DEBUG] wire - http-outgoing-0 >> "{"jsonrpc":"2.0","method":"personal_unlockAccount","params":["0x36707d4b8c69b771291745c221e0b4525ede43e1","hht585945",30],"id":1}"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "Vary: Origin[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "Date: Tue, 20 Dec 2016 06:57:28 GMT[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "Content-Length: 94[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "[\r][\n]"
2016/12/20 14:57:28:354 CST [DEBUG] wire - http-outgoing-0 << "{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"no key for given address or file"}}[\n]"
````

testnet environment.
I have check many times,the accoountId and password is correct，Can someone tell me why please?thanks!

**Comment by karalabe** [comment]
Can you unlock the account from the Geth console?

**Comment by karalabe** [comment]
Please make sure that the account is listed if you type `eth.accounts` inside the Geth console. Afterwards please make sure you can unlock it via `personal.unlockAccount("...")` from within the console.

**Comment by hht0423** [comment]
thanks you very much for your reply!!

I want to  check it with command line "geth --keystore --unlock 36707d4b8c69b771291745c221e0b4525ede43e1  --password hht585945" ，have  a problem like this :
Fatal: Error starting protocol stack: listen tcp :30303: bind: Only one usage of
 each socket address (protocol/network address/port) is normally permitted.

**Comment by hht0423** [comment]
by the way ,all my account list here: 
C:\Windows\system32>geth account list
Account #0: {850297d14249496ed550ce80483bc983706f58de} C:\Users\MyPC\AppData\Roa
ming\Ethereum\keystore\UTC--2016-12-20T02-06-51.675933600Z--850297d14249496ed550
ce80483bc983706f58de
Account #1: {36707d4b8c69b771291745c221e0b4525ede43e1} C:\Users\MyPC\AppData\Roa
ming\Ethereum\keystore\UTC--2016-12-20T03-35-31.147664100Z--36707d4b8c69b7712917
45c221e0b4525ede43e1

**Comment by hht0423** [comment]
Great! the problem have been resolved，the account created by "geth account new" can not use regular，so I change my way to get the keystore created by"personal.newAccount()" ,then everything is ok.
I do not know why.

**Comment by heiyuhao** [comment]
I get the same error.But i still dont know how to solve it.How to get the keystore?This is my way to get the keystore.
ObjectMapper objectMapper = ObjectMapperFactory.getObjectMapper();
WalletFile walletFile = objectMapper.readValue(creStr, WalletFile.class);
Credentials.create(Wallet.decrypt(password, walletFile));

**Comment by tailongwang** [comment]
@karalabe Me too
`curl --data '{"method":"personal_unlockAccount","params":["0x*********","",null],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"no key for given address or file"}}`
