### ISSUE TITLE
[MINER] Nonce err. Is 12, expected 7

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#476]
with `develop` 80592f2

creating trivial contract https://github.com/jorisbontje/sleth/blob/master/contracts/simple.se with hex code `336000556001600155604f8060146000396063567c01000000000000000000000000000000000000000000000000000000006000350463119fbbd48114156036576001600154016001555b63ea66cf6d811415604d5760015460405260206040f35b505b6000f3`

via rpc:
```
{'params': [{'gas': '0x186a0', 'from': '0x48574ed8323453c2c5deaebc69eb068c1cc516fa', 'data': '0x336000556001600155604f8060146000396063567c01000000000000000000000000000000000000000000000000000000006000350463119fbbd48114156036576001600154016001555b63ea66cf6d811415604d5760015460405260206040f35b505b6000f3', 'value': '0x0', 'gasPrice': '0x9184e72a000'}], 'jsonrpc': '2.0', 'id': '64014be1-3810-4964-904b-ad14b86fd945', 'method': 'eth_sendTransaction'}
```
result:
```
{u'jsonrpc': u'2.0', u'id': u'64014be1-3810-4964-904b-ad14b86fd945', u'result': u'0x320fdb74aa01379b2e8189b2daf889a45f6dc306'}
```

ethereum started with:
```
$ ethereum -mine=true -rpc=true -rpcport=8080 --unlock=48574ed8323453c2c5deaebc69eb068c1cc516fa:bla
```

the `ethereum` logs:
```
2015/03/13 13:10:30 [XETH] Contract addr 320fdb74aa01379b2e8189b2daf889a45f6dc306
2015/03/13 13:10:32 [MINER] Hash rate: 88 Khash
2015/03/13 13:10:33 [CHAIN] processed block #1539 (d5aea773...)
2015/03/13 13:10:33 [MINER] committing new work with 1 txs
2015/03/13 13:10:33 [MINER] Nonce err. Is 12, expected 7
2015/03/13 13:10:33 [MINER] (re)started agent[0]. mining...
2015/03/13 13:10:34 [MINER] Hash rate: 91 Khash
2015/03/13 13:10:35 [CHAIN] processed block #1540 (eaecc1ad...)
```

Why does this cause a `Nonce err`? My contract doesn't seem to be mined (`getData` doesnt return anything), but otherwise I get no error messages.

**Comment by obscuren** [comment]
Could you update to https://github.com/ethereum/go-ethereum/commit/f1fcda4f2fe05e46e3d350cb89a52fd33df3767f and see if the error persists. Nonce errors may still be caused when doing something like:

```
send TX1 with too little gas = GAS_FAILURE (nonce 0)
send TX2 with enough gas = OK (nonce 1)
```

Both of these transactions will fail  because: `TX1` fails because of `GAS_FAILURE` and gets removed. `TX2` fails because it actually should have gotten `N = 0`.

The following test should pass
```
send TX1 with too little gas = GAS_FAILURE (nonce 0)
send TX2 with enough gas = OK (nonce 1)
MINE TX1 & 2
send TX3 with enough gas = OK (nonce 0)
```

When TX3 is send it knows of the failure of `TX1` and removes both 1 & 2.

https://github.com/ethereum/go-ethereum/issues/477

**Comment by jorisbontje** [comment]
2015/03/13 17:07:37 [MINER] Nonce err. Is 18446744073709551615, expected 1

**Comment by obscuren** [comment]
Fixed

**Comment by jorisbontje** [comment]
Ok, not getting this error anymore; however my transaction still isn't mining due to
```
[CHAIN] Block timestamp equal or less than previous block (1426267746 - 1426267746)
```

**Comment by obscuren** [comment]
That error doesn't remove the transaction. If a transaction is included in a block that throws an error like the one above it will also be included in the next `valid` one.

**Comment by obscuren** [comment]
Please re-open if the issues persists. I haven't been able to find any nonce errors anymore
