### ISSUE TITLE
RPC sendTransaction: Known transaction

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/go-ethereum#662]
Occasionally I am getting the error message `Known transaction (hex)` when calling the RPC method `sendTransaction`. Hard to reproduce, but easiest to make this happen is when I am playing `sleth` on autoplay.

My `geth` node (`develop` version 7c0a18e) is running as:
```
geth -mine -rpc -rpcport=8080 -unlock=primary -password=/Users/mids/.ethereum/bla --rpccorsdomain=http://localhost:8000
```

JSON RPC request:
```
{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x468b0d4d93b7814ecc63195b1d20f96629972e16","gas":"0x30d40","value":"0x4563918244f40000","to":"0xa78cbedf8b6a932a323599a31979d95e20c5a6ba","data":"0x26638a380000000000000000000000000000000000000000000000000000000000000005"}],"id":608}
```

Response:
```
{
	"id": 608,
	"jsonrpc": "2.0",
	"error": {
		"code": -32603,
		"message": "Known transaction (3b7baba5)"
	}
}
```

There are no obvious warnings/errors in the `geth` log.

**Comment by tcoulter** [comment]
Hi Joris. I'm getting this too. An easy workaround I've found is to alter the amount of gas you want to purchase (i.e., the `gas` param). I'm using web3 in coffeescript, so it'd look something like this:

```coffeescript
#!/usr/bin/env ./node_modules/.bin/coffee
web3 = require "web3"
provider = new web3.providers.HttpProvider("http://#{host}:#{port}")
provider.sendAsync
  jsonrpc: "2.0"
  method: "eth_sendTransaction"
  params: [{
    from: coinbase
    gas: web3.toHex(100000)
    gasPrice: web3.toHex(10000),
    data: "#{code}"
  }]
  id: 1
, (err, result) ->
  console.log err, result
  callback(err, result)
```

If I increment the gas purchase amount by 1, say `web3.toHex(100001)`, the transaction will go through. Note I need to keep incrementing the purchase amount to continue making a successful transaction.

If you put the above in a script and alter your geth host/port, as well as adding your code to the `data` param, it should be easily reproducible. That said, I wouldn't be surprised if it had something to do with similar transactions being executed in rapid succession before they can be processed by your client (<-- a guess).

**Comment by obscuren** [comment]
Thanks. I'm guessing the managed nonce isn't properly incremented. I'll have a look tonight

**Comment by ethers** [comment]
may be related to #694  (I also see ``I0413 13:53:46.671828    1583 transaction_pool.go:168] Known transaction (c172bcaa)
``)

**Comment by obscuren** [comment]
This should be fixed in https://github.com/ethereum/go-ethereum/commit/8310bcda6100cc703f5c1e22e0122ad7476d689d

**Comment by ethers** [comment]
On develop 8db7b23  still seeing Known transaction (hex) when calling the RPC method sendTransaction:
https://gist.github.com/ethers/458ce2d9978b55407a6e

**Comment by zelig** [comment]
@ethers can you confirm if this is still an issue

**Comment by jorisbontje** [comment]
@zelig still seeing this as of 2f4cc72

**Comment by obscuren** [comment]
Yes still an issue => https://github.com/ethereum/go-ethereum/pull/769

**Comment by ethers** [comment]
I am still seeing this issue on develop 8d09f95

**Comment by jorisbontje** [comment]
@obscuren lease reopen; still getting this occasionally.

**Comment by arhuaco** [comment]
I am still seeing this. I am testing with a simple contract that holds a counter.

    while(1){
        var before =  thetest.step();
        many(10);
        while(thetest.step() < before + 10);
    }

    Error response: Known transaction (b13097f5)
    Invalid JSON RPC response
        at InvalidResponse (<anonymous>:-49900:-89)
        at send (<anonymous>:-94858:-89)
        at sendTransaction (<anonymous>:-87064:-89)
        at sendTransaction (<anonymous>:-76490:-89)
        at mine (<anonymous>:1:21)
        at many (<anonymous>:1:50)
        at <anonymous>:1:41

**Comment by arhuaco** [comment]
Something I noticed is that the (partial) hash that I get in the error message matches a transaction that was already sent (by grepping the log file).

**Comment by fjl** [comment]
This should be resolved with #1409. If anyone has the time, please re-test.

**Comment by ethers** [comment]
still see this on RC2

```
I0709 11:47:44.362565    4261 mergedapi.go:61] eth_sendTransaction [{"value":"0x25bf6196bd10000","gas":"0x7a120","to":"0x39dfd4315e8b90488ab57e58e4d8b4597a1511e6","data":"0x66f7e56c000000000000000000000000a0dc485fc3ade71be5e1b68397abded386c0adb7000000000000000000000000000000000000000000000000025bf6196bd10000000000000000000000000000000000000000000000000000000000e8d4a51000","from":"0xcd2a3d9f938e13cd947ec05abc7fe734df8dd826"}]
I0709 11:47:44.364493    4261 transaction_pool.go:241] (t) 6364326133643966 => 39dfd431 (0x5185a0) 571318488d169d46c84b3ba0764e905b21ce45d17a7082bc7428911c15c42bb6
I0709 11:47:44.365406    4261 types.go:105] Generated response: *shared.SuccessResponse &{%!s(float64=153) 2.0 0x571318488d169d46c84b3ba0764e905b21ce45d17a7082bc7428911c15c42bb6}
I0709 11:47:44.365463    4261 http_net.go:123] Sending payload: {
	"id": 153,
	"jsonrpc": "2.0",
	"result": "0x571318488d169d46c84b3ba0764e905b21ce45d17a7082bc7428911c15c42bb6"
}

I0709 11:47:44.697887    4261 transaction_pool.go:292] tx error: Known transaction (57131848)
I0709 11:47:44.742878    4261 transaction_pool.go:292] tx error: Known transaction (57131848)

```

**Comment by jorisbontje** [comment]
Haven't seen this for ages. Closing

**Comment by fastandscalable** [comment]
Just happened to me with web3 and geth v1.5.5-stable.

**Comment by himanshuoodles** [comment]
Known transaction: 9e2a172c error coming in geth v1.5.7

**Comment by PositronicBrain** [comment]
Same here, using geth version 1.5.9. I have a small nodejs program which sends rpc transactions, specifically using the call `sendTransaction`, to a private geth node which runs on my machine. The program iterates many times the operation of moving ether from one account to another. Around 1% of the transactions produces the error message:

    [Error: Known transaction: 09fd57d9]

**Comment by jtakalai** [comment]
Same error, geth 1.5.9-stable-a07539fb

**Comment by Asiron** [comment]
Same error happening on `1.6.0-stable-facc47cb`

**Comment by nirvanaGNR** [comment]
I build a private chain, and there is still this problem:
---------------------------------------Test----------------------------------------------
this is test:
fnatic@vmnode3:~/testcontract$ curl --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x667deaf964ee2520ac701d649bd27a013bdd7831","to":"0xa30665086f13a561dd33703e82ef4c5b8dbf91a1","data":"0x867904b4000000000000000000000000667deaf964ee2520ac701d649bd27a013bdd7831000000000000000000000000000000000000000000000000000000000000002a"}],"id":2}' 192.168.10.239:8545

{"jsonrpc":"2.0","id":2,"error":{"code":-32000,"message":"**known transaction**: f8236a44585005362db80b7a5f041f9fa53e6051e4b5f978a06886d4fff9d452"}}

---------------------------------------Version information----------------------------------------------
fnatic@vmnode3:~/testcontract$ geth version 
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

**Comment by davux** [comment]
@jorisbontje Can you please reopen? The bug is still there, according to all these people.
I'm seeing it too on geth 1.7.3.

**Comment by bijlar** [comment]
I'm seeing it as well on version `v1.7.3-stable-4bb3c89d`.

**Comment by flexsingit** [comment]
Hello Everyone, 

I am aslo seeing the same issue can anyone please help.

I am creating 4 diffrent transactions with different amounts and i am facing the issue.

Help Please.
Regards,
Himanshu

**Comment by aleczadikian** [comment]
Same thing happening to me. Can't find a pattern. I retry the same thing until it works.

**Comment by malaki12003** [comment]
this is a shit problem

**Comment by folex** [comment]
Still happening on Geth/v1.8.7 with web3j 3.4.0

**Comment by 377872755** [comment]
still happening on geth/v1.8.12-stable with jsonrpc   {"code":-32000,"message":"known transaction: a5307010de7aa330a7eecbc88b456e2397c531bd0b99643cf59a77a14d5eb541"}}

**Comment by 377872755** [comment]
Still happening on Geth/v1.8.12-stable with jsonrpc   {"code":-32000,"message":"known transaction: *******"}}

**Comment by EBGToo** [comment]
Still happening on Geth/v1.8.14

**Comment by halink0803** [comment]
I just got this error on Geth/v1.8.27. Does anyone know how to fix this?

**Comment by rite2bala** [comment]
I got this error .. any fixes?

**Comment by fnaticwang** [comment]
> I got this error .. any fixes?

Maybe you set the same nonce value,this results in a duplicate hash being generateds, and you need to set the incremental nonce
