### ISSUE TITLE
Windows crash after DAG generation

### ISSUE THREAD

**Issue by Quiark** [ethereum/go-ethereum#827]
In short, it crashes because it tries to load the wrong path:
```
I0429 11:39:21.558773    5604 ethash.go:136] ... still generating DAG (825.0001873) ...
I0429 11:39:22.967854    5604 ethash.go:138] ... DAG generation completed ...
panic: open /tmp/dag: The system cannot find the path specified.
```

Details:
Downloaded the build `Geth-Win64-20150428110804-0.9.12-60--a6a49cc.7z` (a previous build had the same problem), then did

```geth console
admin.newAccount()
admin.miner.start()
```
got expected result

```
I0429 11:25:34.912492    5604 ethash.go:94] Making cache for epoch: 6 (198524) (582b06447f087674bcc0a32a19961e77dafb9e17955792f79ec8936e3d9742fc)
true←[0m
> I0429 11:25:36.557586    5604 ethash.go:99] Took: 1.6440941s
I0429 11:25:36.557586    5604 ethash.go:198] Retrieving DAG
I0429 11:25:36.557586    5604 ethash.go:203] No DAG found. Generating new DAG in '/tmp/dag' (this takes a while)...
I0429 11:25:39.978781    5604 chain_manager.go:605] imported 1 block(s) 0 queued in 13.0007ms. #198525 [aaa5e26b / aaa5e26b]
I0429 11:25:41.558872    5604 ethash.go:136] ... still generating DAG (5.000286) ...
I0429 11:25:46.559158    5604 ethash.go:136] ... still generating DAG (10.000572) ...
I0429 11:25:51.559444    5604 ethash.go:136] ... still generating DAG (15.000858) ...
I0429 11:25:51.959467    5604 chain_manager.go:605] imported 1 block(s) 0 queued in 7.0004ms. #198526 [667e7798 / 667e7798]
I0429 11:25:56.558730    5604 ethash.go:136] ... still generating DAG (20.0001439) ...
```

but then after finished it crashed with the message above. See http://pastebin.com/50Sq2QVP for full log

**Comment by Quiark** [comment]
It seems like a general path problem, after starting again it can't find my previous account

```
> admin.unlock()
Please enter a passphrase now.
Passphrase:
Unlock account failed 'read C:\Users\Roman/AppData/Roaming/Ethereum/keys: The handle is invalid.'
false←[0m
```

**Comment by tgerring** [comment]
We should replace all instances of filesystem-related "/" or "\" with http://golang.org/pkg/os/#PathSeparator or use http://golang.org/pkg/path/#Join

**Comment by obscuren** [comment]
PR #828 merged. Could you test again @Quiark ?

**Comment by Quiark** [comment]
I downloaded this build https://build.ethdev.com/builds/Windows%20Go%20develop%20branch/Geth-Win64-20150429085552-0.9.12-60--32373e3.7z

No change. geth is still trying to open `/tmp/dag` which is not going to work on Windows. I found in `\ethereum\ethash\ethash.go` in `writeDagToDisk` hardcoded `/tmp/dag` path.

For the keys, I still get that error even though the path exists:

```
PS C:\Devel\ether\go-ethereum> ls C:\Users\Roman/AppData/Roaming/Ethereum/keys


    Directory: C:\Users\Roman\AppData\Roaming\Ethereum\keys


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         29.4.2015     10:44            10851e84266f0393d1f6a5e5c891452b2a12ff12
d----         29.4.2015     17:00            9bbf9dceaba1b92cc6ad086921591f40dd6febf0
d----         29.4.2015     11:52            c82bc8e28e26b6d3446ee9ab39a79426ec2fd16c
d----         29.4.2015     11:25            e503c078f38d852dc6d4447d0ccbd3a2b61744a0

```

**Comment by maran** [comment]
This is pretty weird. I made a PR to fix this in ethereum/ethash#13 but @LefterisJP closed it because it was already fixed. Perhaps he could comment?

**Comment by fjl** [comment]
It is fixed In the ethash rewrite, which hasn't been merged yet.

**Comment by LefterisJP** [comment]
what he said.
Sorry for taking so long to merge. There are many issues that have come up in the meantime. Merging that PR on master may still not mean that it's gonna be immediately used by go-ethereum so maybe you could take a patch of maran's prorposed change and add it in go-ethereum temporarily so that users don't have this problem?

**Comment by drocta** [comment]
This seems (to me) to work now, with the build linked in the readme.
